0 0 dataAuditErrors
2 0 # INFO: I/O PADS = WIREBOND #
129 0 ERROR: CA(net) not covered by CA(drawing) found!
132 0 ERROR: CABAR(net) not covered by CABAR(drawing) found!
135 0 ERROR: E2(net) not covered by E2(drawing) found!
138 0 ERROR: FT(net) not covered by FT(drawing) found!
141 0 ERROR: NS(net) not covered by NS(drawing) found!
144 0 ERROR: NW(net) not covered by NW(drawing) found!
147 0 ERROR: V1(net) not covered by V1(drawing) found!
150 0 ERROR: V1BAR(net) not covered by V1BAR(drawing) found!
153 0 ERROR: V2(net) not covered by V2(drawing) found!
156 0 ERROR: V2BAR(net) not covered by V2BAR(drawing) found!
159 0 ERROR: V3(net) not covered by V3(drawing) found!
162 0 ERROR: V3BAR(net) not covered by V3BAR(drawing) found!
165 0 ERROR: V4(net) not covered by V4(drawing) found!
168 0 ERROR: V4BAR(net) not covered by V4BAR(drawing) found!
171 0 ERROR: V5(net) not covered by V5(drawing) found!
174 0 ERROR: V5BAR(net) not covered by V5BAR(drawing) found!
177 0 ERROR: AM(net or pin) not covered by AM(drawing) found!
180 0 ERROR: DV(net or pin) not covered by DV(drawing) found!
183 0 ERROR: E1(net or pin) not covered by E1(drawing) found!
186 0 ERROR: LV(net or pin) not covered by LV(drawing) found!
189 0 ERROR: M1(net or pin) not covered by M1(drawing) found!
192 0 ERROR: M2(net or pin) not covered by M2(drawing) found!
195 0 ERROR: M3(net or pin) not covered by M3(drawing) found!
198 0 ERROR: M4(net or pin) not covered by M4(drawing) found!
201 0 ERROR: M5(net or pin) not covered by M5(drawing) found!
204 0 ERROR: MA(net or pin) not covered by MA(drawing) found!
207 0 ERROR: ML(net or pin) not covered by ML(drawing) found!
210 0 ERROR: MT(net or pin) not covered by MT(drawing) found!
212 0 ERROR: NW(net or pin) not covered by NW(drawing) found!
215 0 ERROR: RX(net or pin) not covered by RX(drawing) found!
218 0 ERROR: PC(net) not covered by PC(drawing) found!
222 0 ERROR: PC(pin) not covered by PC(drawing) found!
223 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BF)
224 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BH)
225 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BN)
226 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DE)
227 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DF)
228 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (PH)
229 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (AMFILL)
230 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (E1FILL)
231 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M1FILL)
232 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M2FILL)
233 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M3FILL)
234 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M4FILL)
235 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M5FILL)
236 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MAFILL)
237 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MLFILL)
238 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MTFILL)
239 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (PCFILL)
240 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (RXFILL)
242 0 GRPN001: Shape straddling LOGOBND found! (AM)
244 0 GRPN001: Shape straddling LOGOBND found! (BB)
245 0 GRPN001: Shape straddling LOGOBND found! (BF)
247 0 GRPN001: Shape straddling LOGOBND found! (BFMOAT)
248 0 GRPN001: Shape straddling LOGOBND found! (BH)
250 0 GRPN001: Shape straddling LOGOBND found! (BHRES)
251 0 GRPN001: Shape straddling LOGOBND found! (BN)
253 0 GRPN001: Shape straddling LOGOBND found! (BP)
255 0 GRPN001: Shape straddling LOGOBND found! (BPRES)
256 0 GRPN001: Shape straddling LOGOBND found! (CA)
257 0 GRPN001: Shape straddling LOGOBND found! (CABAR)
259 0 GRPN001: Shape straddling LOGOBND found! (CAP)
260 0 GRPN001: Shape straddling LOGOBND found! (DE)
261 0 GRPN001: Shape straddling LOGOBND found! (DF)
263 0 GRPN001: Shape straddling LOGOBND found! (DG)
265 0 GRPN001: Shape straddling LOGOBND found! (DI)
266 0 GRPN001: Shape straddling LOGOBND found! (DV)
268 0 GRPN001: Shape straddling LOGOBND found! (HT)
270 0 GRPN001: Shape straddling LOGOBND found! (K1)
271 0 GRPN001: Shape straddling LOGOBND found! (M1)
273 0 GRPN001: Shape straddling LOGOBND found! (M1CHEXCL)
274 0 GRPN001: Shape straddling LOGOBND found! (M2)
275 0 GRPN001: Shape straddling LOGOBND found! (M3)
276 0 GRPN001: Shape straddling LOGOBND found! (M4)
277 0 GRPN001: Shape straddling LOGOBND found! (M5)
279 0 GRPN001: Shape straddling LOGOBND found! (MOSVAR)
280 0 GRPN001: Shape straddling LOGOBND found! (MT)
281 0 GRPN001: Shape straddling LOGOBND found! (NS)
282 0 GRPN001: Shape straddling LOGOBND found! (NW)
284 0 GRPN001: Shape straddling LOGOBND found! (NWASP)
286 0 GRPN001: Shape straddling LOGOBND found! (OP)
287 0 GRPN001: Shape straddling LOGOBND found! (PC)
289 0 GRPN001: Shape straddling LOGOBND found! (PCING)
291 0 GRPN001: Shape straddling LOGOBND found! (PD)
293 0 GRPN001: Shape straddling LOGOBND found! (PCFUSE)
294 0 GRPN001: Shape straddling LOGOBND found! (PH)
296 0 GRPN001: Shape straddling LOGOBND found! (PHRES)
298 0 GRPN001: Shape straddling LOGOBND found! (PI)
300 0 GRPN001: Shape straddling LOGOBND found! (QT)
302 0 GRPN001: Shape straddling LOGOBND found! (RN)
304 0 GRPN001: Shape straddling LOGOBND found! (RP)
306 0 GRPN001: Shape straddling LOGOBND found! (RR)
307 0 GRPN001: Shape straddling LOGOBND found! (RX)
308 0 GRPN001: Shape straddling LOGOBND found! (V1)
309 0 GRPN001: Shape straddling LOGOBND found! (V1BAR)
310 0 GRPN001: Shape straddling LOGOBND found! (V2)
311 0 GRPN001: Shape straddling LOGOBND found! (V2BAR)
312 0 GRPN001: Shape straddling LOGOBND found! (V3)
313 0 GRPN001: Shape straddling LOGOBND found! (V3BAR)
314 0 GRPN001: Shape straddling LOGOBND found! (V4)
315 0 GRPN001: Shape straddling LOGOBND found! (V4BAR)
316 0 GRPN001: Shape straddling LOGOBND found! (V5)
317 0 GRPN001: Shape straddling LOGOBND found! (V5BAR)
321 0 GRPN203: CA to CA space (logo) >= 0.400 um.
324 0 GRPN502: M1 to M1 space (logo) >= 0.400 um.
326 0 GRPN502: M1 to M1 notch (logo) >= 0.400 um.
338 0 GRPN553: V1 to V1 space (logo) >= 0.400 um.
340 0 GRPN553: V2 to V2 space (logo) >= 0.400 um.
342 0 GRPN553: V3 to V3 space (logo) >= 0.400 um.
344 0 GRPN553: V4 to V4 space (logo) >= 0.400 um.
346 0 GRPN553: V5 to V5 space (logo) >= 0.400 um.
353 0 GRPN602: M2 to M2 space (logo) >= 0.400 um.
355 0 GRPN602: M3 to M3 space (logo) >= 0.400 um.
357 0 GRPN602: M4 to M4 space (logo) >= 0.400 um.
359 0 GRPN602: M5 to M5 space (logo) >= 0.400 um.
361 0 GRPN602: MT to MT space (logo) >= 0.400 um.
363 0 GRPN602: M2 to M2 notch (logo) >= 0.400 um.
365 0 GRPN602: M3 to M3 notch (logo) >= 0.400 um.
367 0 GRPN602: M4 to M4 notch (logo) >= 0.400 um.
369 0 GRPN602: M5 to M5 notch (logo) >= 0.400 um.
371 0 GRPN602: MT to MT notch (logo) >= 0.400 um.
372 0 GRPN907: DV over LOGOBND found!
407 0 # INFO: 3 Level Metal (M1+MT+AM) #
408 0 # INFO: 4 Level Metal (M1+M2+MT+AM) #
409 0 # INFO: 5 Level Metal (M1+M2+M3+MT+AM) #
410 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+AM) #
411 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+AM) #
414 0 # INFO: 4 Level Metal (M1+MT+E1+MA) #
415 0 # INFO: 5 Level Metal (M1+M2+MT+E1+MA) #
416 0 # INFO: 6 Level Metal (M1+M2+M3+MT+E1+MA) #
417 0 # INFO: 7 Level Metal (M1+M2+M3+M4+MT+E1+MA) #
418 0 # INFO: 8 Level Metal (M1+M2+M3+M4+M5+MT+E1+MA) #
421 0 # INFO: 3 Level Metal (M1+MT+ML) #
422 0 # INFO: 4 Level Metal (M1+M2+MT+ML) #
423 0 # INFO: 5 Level Metal (M1+M2+M3+MT+ML) #
424 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+ML) #
425 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+ML) #
430 0 WARNING: MULTIPLE LAST METAL LEVELS FOUND! (AM or MA or ML)
574 0 GRPHHOLE7: PHHOLE1 enclosed area >= 0.537 sq.um.
575 0 GRPHHOLE8: ((PC over RX) over NW) touching PHHOLE1 found!
576 0 GRPHHOLE8: ((PC over RX) over NW) to PHHOLE1 space >= 0.360 um.
578 0 WARNING: GridCheck NOT RUN!
591 0 ERROR: FUSES FOUND! - LASER FUSES ARE NOT OFFERED WITH ANALOG METAL! (AM,MA,ML)
593 0 ERROR: FUSES FOUND! - LASER FUSES ARE NOT OFFERED WITH ANALOG METAL! (AM,MA,ML)
630 0 GR990a: RX(chipring) width >= 1.080 um.
631 0 GR990b: BP(chipring) width >= 1.520 um.
632 0 GR990f: M1(chipring) width >= 1.080 um.
633 0 GR990f: M2(chipring) width >= 1.080 um.
634 0 GR990f: M3(chipring) width >= 1.080 um.
635 0 GR990f: M4(chipring) width >= 1.080 um.
636 0 GR990f: M5(chipring) width >= 1.080 um.
637 0 GR990g: MT(chipring) width >= 3.240 um.
638 0 GR990h: E2(chipring) width >= 2.000 um.
639 0 GR990i: E1(chipring) width >= 3.240 um.
640 0 GR990k: AM(chipring) width >= 2.000 um.
641 0 GR990k: MA(chipring) width >= 4.000 um.
642 0 GR990k: ML(chipring) width >= 2.400 um.
643 0 GR990c: BP(chipring) touching BB found!
652 0 GR990d: CABAR(chipring) width == 0.200 um. (error >)
653 0 GR990d: CABAR(chipring) width == 0.200 um. (error <)
662 0 GR990e: V1BAR(chipring) width == 0.280 um. (error >)
663 0 GR990e: V1BAR(chipring) width == 0.280 um. (error <)
672 0 GR990e: V2BAR(chipring) width == 0.280 um. (error >)
673 0 GR990e: V2BAR(chipring) width == 0.280 um. (error <)
682 0 GR990e: V3BAR(chipring) width == 0.280 um. (error >)
683 0 GR990e: V3BAR(chipring) width == 0.280 um. (error <)
692 0 GR990e: V4BAR(chipring) width == 0.280 um. (error >)
693 0 GR990e: V4BAR(chipring) width == 0.280 um. (error <)
702 0 GR990e: V5BAR(chipring) width == 0.280 um. (error >)
703 0 GR990e: V5BAR(chipring) width == 0.280 um. (error <)
712 0 GR990j: FTBAR(chipring) width == 1.240 um. (error >)
713 0 GR990j: FTBAR(chipring) width == 1.240 um. (error <)
714 0 GR991: RX not within BP(chipring) found!
716 0 GR991: RX must be within BP(chipring) >= 0.220 um.
717 0 GR992: CABAR not within RX(chipring) found!
719 0 GR992: CABAR must be within RX(chipring) >= 0.440 um.
720 0 GR993: CABAR not within M1(chipring) found!
722 0 GR993: CABAR must be within M1(chipring) >= 0.440 um.
723 0 GR994a: V1BAR not within M1(chipring) found!
725 0 GR994a: V1BAR must be within M1(chipring) >= 0.400 um.
726 0 GR994b: V2BAR not within M2(chipring) found!
728 0 GR994b: V2BAR must be within M2(chipring) >= 0.400 um.
729 0 GR994c: V3BAR not within M3(chipring) found!
731 0 GR994c: V3BAR must be within M3(chipring) >= 0.400 um.
732 0 GR994d: V4BAR not within M4(chipring) found!
734 0 GR994d: V4BAR must be within M4(chipring) >= 0.400 um.
735 0 GR994d1: V5BAR not within M5(chipring) found!
737 0 GR994d1: V5BAR must be within M5(chipring) >= 0.400 um.
738 0 GR994e: FTBAR not within MT(chipring) found!
740 0 GR994e: FTBAR must be within MT(chipring) >= 1.000 um.
742 0 GR994f: FTBAR not within AM(chipring) found!
744 0 GR994f: FTBAR must be within AM(chipring) >= 1.000 um.
746 0 GR994f: FTBAR not within E1(chipring) found!
748 0 GR994f: FTBAR must be within E1(chipring) >= 1.000 um.
750 0 GR994f: FTBAR not within ML(chipring) found!
752 0 GR994f: FTBAR must be within ML(chipring) >= 0.600 um.
754 0 GR995a: V1BAR not within M2(chipring) found!
756 0 GR995a: V1BAR must be within M2(chipring) >= 0.400 um.
759 0 GR995b: V1BAR not within MT(chipring) found!
761 0 GR995b: V1BAR must be within MT(chipring) >= 0.400 um.
763 0 GR996a: V2BAR not within M3(chipring) found!
765 0 GR996a: V2BAR must be within M3(chipring) >= 0.400 um.
768 0 GR996b: V2BAR not within MT(chipring) found!
770 0 GR996b: V2BAR must be within MT(chipring) >= 0.400 um.
772 0 GR996c: V3BAR not within M4(chipring) found!
774 0 GR996c: V3BAR must be within M4(chipring) >= 0.400 um.
777 0 GR996d: V3BAR not within MT(chipring) found!
779 0 GR996d: V3BAR must be within MT(chipring) >= 0.400 um.
782 0 GR996e: V4BAR not within MT(chipring) found!
784 0 GR996e: V4BAR must be within MT(chipring) >= 0.400 um.
786 0 GR996f: V4BAR not within M5(chipring) found!
788 0 GR996f: V4BAR must be within M5(chipring) >= 0.400 um.
790 0 GR996g: V5BAR not within MT(chipring) found!
792 0 GR996g: V5BAR must be within MT(chipring) >= 0.400 um.
793 0 GR996h: E2 not within E1(chipring) found!
795 0 GR996h: E2 must be within E1(chipring) >= 0.600 um.
796 0 GR996j: E2 not within MA(chipring) found!
798 0 GR996j: E2 must be within MA(chipring) >= 1.760 um.
805 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error >)
813 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error >)
821 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error >)
829 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error >)
837 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error >)
844 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error >)
846 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error <)
848 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error <)
850 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error <)
852 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error <)
854 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error <)
856 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error <)
857 0 GR999b: BP(guardring) straddling CHIPEDGE found!
859 0 GR999b: BP(guardring) within CHIPEDGE >= 9.280 um.
868 0 GR999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error >)
870 0 GR999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error <)
879 0 GR999c: E1(ring) must be within CHIPEDGE == 11.06 um.(error >)
881 0 GR999c: E1(ring) must be within CHIPEDGE == 11.06 um.(error <)
890 0 GR999c: MA(ring) must be within CHIPEDGE == 11.06 um.(error >)
892 0 GR999c: MA(ring) must be within CHIPEDGE == 11.06 um.(error <)
901 0 GR999c: ML(ring) must be within CHIPEDGE == 11.06 um.(error >)
903 0 GR999c: ML(ring) must be within CHIPEDGE == 11.06 um.(error <)
911 0 GR999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error >)
913 0 GR999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error <)
916 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (AM)
919 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (MA)
922 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (ML)
923 0 GR1: (PC over RX)(NFET) width >= 0.180 um.
924 0 GR2: (PC over RX)(PFET) width >= 0.180 um.
926 0 GR3: (PC over RX)(NFET) width for 45 deg >= 0.196 um.
928 0 GR4: (PC over RX)(PFET) width for 45 deg >= 0.196 um.
932 0 GR10: RX width under PC for NFET device >= 0.220 um.
934 0 GR11: RX width under PC for PFET device >= 0.220 um.
943 0 GR50b: RX width (max) <= 200.000 um.
944 0 GR50: RX width (min) >= 0.220 um.
945 0 GR51: RX area >= 0.160 sq.um.
947 0 GR52: RX space >= 0.260 um.
949 0 GR52: RX notch >= 0.260 um.
950 0 GRCPRX4: RX straddling NS found!
952 0 GRCPRX4: RX within NS >= 0.500 um.
961 0 GRRX8b: (BF not touching NW) to adjacent NW >= 1.140 um.
962 0 GRRX8d: ((BF touch NW) touch NWASP) to adj (NW over NWASP) >= 0.700 um.
974 0 GRRX23: RX(over BB, not IND_FLT, not PC) not covered by {PD,RN,JD,SBD} found!
1002 0 GR100: PC width >= 0.180 um.
1006 0 GR101a: PC area >= 0.203 sq. um.
1007 0 GR101b: PC enclosed area >= 0.291 sq. um.
1041 0 GR102a: PC(not over RX) space (run <= 0.18) >= 0.240 um.
1043 0 GR102a: PC(not over RX) space (run > 0.18) >= 0.240 um.
1047 0 GR102a: PC(not over RX) notch >= 0.240 um.
1049 0 GR102b: PC to PC (including PCEND) (not over RX) space >= 0.180 um.
1052 0 GR104a/b: PC(over RX) space >= 0.240 um.
1058 0 GR110: RX overlap past PC >= 0.280 um.
1060 0 GR110: RX overlap past PC >= 0.280 um.(coincident)
1062 0 GR110: RX overlap past PC >= 0.280 um.(45 deg. gate)
1064 0 GR111: PC overlap past RX >= 0.240 um.
1066 0 GR111: PC overlap past RX >= 0.240 um.(coincident)
1080 0 GR112: PC overlap past RX (within 0.08 of RX corner) >= 0.300 um.
1081 0 GR114: PC to RX corner >= 0.060 um.
1082 0 GR114: PC abutting RX corner found!
1091 0 GR115: PC corner to RX >= 0.080 um.
1092 0 GR115: RX abutting PC corner found!
1105 0 GR119: PC vertex(inside) within RX >= 0.280 um.
1124 0 GR119: PC vertex(outside) within RX >= 0.280 um.
1137 0 GR119: PC vertex(end) within RX >= 0.280 um.
1152 0 GR120a: Non 45 degree PC vertices over RX found!(90 degree)
1153 0 GR120a: Non 45 degree PC vertices over RX found!(non 45)
1155 0 GR120b: Dist between inside corners of 45 degree gate >= 0.080 um.
1157 0 GR120c: (PC over RX) notch >= 0.460 um.
1160 0 GR121: PC intersecting RX at other than 90 degrees found!
1168 0 GR123a: 45 degree outside RX vertice under PC found!
1170 0 GR123a: 90 degree inside RX vertice under PC found!
1178 0 GR123a: 90 degree outside RX vertice under PC found!
1181 0 GR123b: Dist between inside corners of (RX under PC) >= 0.080 um.
1188 0 GR125: (PC over RX) dividing RX into less than 2 diffusions found!
1190 0 GR130b: (PC not intersecting RX) to RX >= 0.080 um.
1192 0 GR132: (PC that intersects RX) area <= 320.000 sq.um.
1193 0 GR200: CA width and length == 0.200 um.(error <)
1194 0 GR200: CA width and length == 0.200 um.(error >)
1197 0 GR201: Non-rectangular CA found!
1198 0 GR201: 45 degree CA or CABAR found
1200 0 GR203a: CA space >= 0.240 um.
1202 0 GR204: CA within RX >= 0.100 um.
1204 0 GR204a: CABAR within RX >= 0.200 um.
1205 0 GR207: CA(over RX) to adjacent PC >= 0.160 um.
1208 0 GR208: CA(over PC) to adjacent RX >= 0.160 um.
1209 0 GR208a: CABAR(over PC) to adjacent RX >= 0.200 um.
1211 0 GR209: CA within PC >= 0.060 um.
1213 0 GR209a: CABAR within PC >= 0.160 um.
1214 0 GR211: {CA,CABAR} over (PC over RX) found!
1216 0 GR212: {CA,CABAR} not over {RX or PC} found!
1226 0 GR220: CABAR width == 0.200 um.(error >)
1227 0 GR220: CABAR width == 0.200 um.(error <)
1229 0 GR221: Non-rectangular CABAR found!
1230 0 GR221: CABAR length (min) >= 0.600 um.
1231 0 GR222: CABAR length (max) <= 5.000 um.
1232 0 GR223c: CA touching CABAR found!
1234 0 GR223a: CABAR space >= 0.360 um.
1236 0 GR223b: CABAR space (run > 2.5) >= 0.520 um.
1237 0 GR223c: CABAR to adjacent CA >= 0.280 um.
1239 0 GR225: CABAR(over RX) to adjacent PC >= 0.240 um.
1244 0 GR228: CABAR outside of (Resistors or Chip Guardring) found!
1245 0 GR250a: Non-orthagonal NW shapes found!
1246 0 GR250: NW(drawn or generated) width >= 0.700 um.
1250 0 GR252c: RX shape between (NW shapes < 1.28 um. apart) found!
1251 0 GRNWASP1: NW straddling NWASP found!
1253 0 GR252a: NW(not over NWASP) space >= 1.280 um.
1254 0 GR252a: NW(not over NWASP) to NW(over NWASP) space >= 1.280 um.
1256 0 GR252b: NW(over NWASP) space (run  < 0.70) >= 1.280 um.
1258 0 GR252b: NW(over NWASP) space (run >= 0.70) >= 0.840 um.
1260 0 GR252b: NW notch (run  < 0.70) >= 1.280 um.
1262 0 GR252b: NW notch (run >= 0.70) >= 0.840 um.
1274 0 GR260: (RX within BP) straddling NW found!
1276 0 GR260: (RX within BP) within NW >= 0.420 um.
1278 0 GR260a: (RX within BP) within NW(>=40.0) >= 0.520 um.
1283 0 GRCP260: (RX(P+) not touching NW) must be within BB >= 1.280 um.
1285 0 GRCP260c: RX(N contact) within BB >= 1.280 um.
1288 0 GR261f: RX(NWcont) overlap of NW >= 0.280 um.
1298 0 GR262: RX(NWcont) overlap area with NW >= 0.150 sq.um.
1299 0 GR262b: (RX within RN) intersect area with BB >= 0.150 sq.um.
1300 0 GR262f: RX(NWcont) overlap area with NW >= 0.240 sq.um.
1302 0 GR265: RX(outside BP) to adjacent NW (diff net) >= 0.420 um.
1303 0 GR265a: RX(outside BP) to adjacent NW(>=40.0) >= 0.520 um.
1305 0 GRCP265b: (RX outside BP) to adj BB (diff net) >= 0.420 um.
1306 0 GR266: (RX(in BP) outside NW) to adjacent NW >= 0.080 um.
1307 0 GRCP266c: (RX(in BP) no NW) to BB space >= 0.400 um.
2240 0 GR268: RX(in BP) to RX(not BP) (in same NW) space <= 53.000 um.
3194 0 GR268b: RX(N+ Jct) to Substrate Contact space <= 53.000 um.
4132 0 GRBB268: (RX over PD) to RX(not over PD) (same BB) space <= 53.000 um.
4136 0 GR268g: NW(hole) without a substrate contact found!
4141 0 GR268g: BB(hole) without a substrate contact found!
4145 0 GR268g: BF(hole) without a substrate contact found!
4149 0 GR268g: BFMOAT(hole) without a substrate contact found!
4151 0 GR269: (PC over RX (where RX Straddles NW)) straddling NW found!
4155 0 GR269a: RX(NWcont) overlap past (NW not over GRLOGIC) >= 0.700 um.
4156 0 GR269: (PC over RX (where RX Straddles NW)) to NW space >= 0.700 um.
4159 0 GRNW4: NW overlapping BB found!
4160 0 GRNW4: NW to adjacent BB >= 1.760 um.
4162 0 GRVTSENS00: (PC over RX) straddling VTSENS found!
4164 0 GRVTSENS01: ((PC over RX) over VTSENS) to BB space >= 3.00 um.
4165 0 GRVTSENS01: ((PC over RX) over VTSENS) to BFMOAT space >= 3.00 um.
4166 0 GRVTSENS01: ((PC over RX) over VTSENS) to MOSVAR space >= 3.00 um.
4167 0 GRVTSENS01: ((PC over RX) over VTSENS) to NW space >= 3.00 um.
4168 0 GRVTSENS01: ((PC over RX) over VTSENS) to ZEROVT space >= 3.00 um.
4170 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) straddling PI found!
4172 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within NW >= 2.30 um.
4174 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within PI >= 2.30 um.
4175 0 GR290: NR width >= 0.640 um.
4176 0 GR291: Non-orthogonal NR shape found!
4178 0 GR292: NR to NR  space >= 0.620 um.
4181 0 GR294a: [(PC intersect RX) not within NW] to NR  space >= 0.260 um.
4182 0 GR294b: [(PC intersect RX) not within NW] straddling NR found!
4184 0 GR294b: [(PC intersect RX) not within NW] within NR >= 0.260 um.
4186 0 GR299b: NR overlap past NW >= 1.400 um.
4190 0 GRNR10 : NR touching (BB, MOSVAR, PD, DI) found!
4191 0 GRNR11 : NR to ZEROVT >= 1.400 um.
4192 0 GRNR11 : NR touching ZEROVT found!
4193 0 GRNR12 : NR to PCFUSE >= 1.400 um.
4194 0 GRNR12 : NR touching PCFUSE found!
4196 0 GRNR13: NR not touching (PC over RX) found!
4197 0 GRLW00: PR width >= 0.640 um.
4198 0 GRLW01: Non-orthogonal PR shape found!
4200 0 GRLW02: PR to PR  space >= 0.620 um.
4203 0 GRLW04a: [(PC intersect RX) not within NW] to PR  space >= 0.260 um.
4204 0 GRLW04b: [(PC intersect RX) not within NW] straddling PR found!
4206 0 GRLW04b: [(PC intersect RX) not within NW] within PR >= 0.260 um.
4207 0 GRLW09: PR overlap past NW >= 0.860 um.
4211 0 GRLW10 : PR touching (BB, MOSVAR, PD, DI) found!
4212 0 GRLW11 : PR to ZEROVT >= 1.400 um.
4213 0 GRLW11 : PR touching ZEROVT found!
4214 0 GRLW12 : PR to PCFUSE >= 1.400 um.
4215 0 GRLW12 : PR touching PCFUSE found!
4217 0 GRLW13: PR not touching (PC over RX) found!
4222 0 GR350: BP width >= 0.340 um.
4227 0 GR351a: BP area >= 0.387 sq.um.
4228 0 GR351b: BP enclosed area >= 0.387 sq.um.
4230 0 GR352: BP space >= 0.340 um.
4232 0 GR352: BP notch >= 0.340 um.
4242 0 GR353: ((RX over BP) over NW) within BP >= 0.140 um.
4246 0 GR353: ((RX over BP) over NW) within BP (coincident) >= 0.140 um.
4247 0 GR353b: (RX over PD) straddling BB found!
4249 0 GR353b: (RX over PD) within BB >= 0.140 um.
4262 0 GR354a: ((RX(sub cont) not GRLOGIC) not (NW +0.42)) within BP >= 0.000 um.
4264 0 GR354b: (RX(sub cont) over (NW +0.42)) within BP >= 0.140 um.
4272 0 GR355: (RX(not over BP)not over NW) to BP space >= 0.140 um.
4278 0 GR356b: (RX(nw cont) not over (NW -0.42)) to adj BP >= 0.140 um.
4279 0 GR357: Layout will cause: BH to NW space >= 0.440 um.
4280 0 GR357: Layout will cause: BH to BB space >= 0.440 um.
4281 0 GR357: Layout will cause: BH to MOSVAR space >= 0.440 um.
4282 0 GR357a: Layout will cause: BH width >= 0.440 um.
4284 0 GR357b: Layout will cause: BH space >= 0.440 um.
4286 0 GR357b: Layout will cause: BH notch >= 0.440 um.
4289 0 GR358b: BP to PD space >= 0.340 um.
4290 0 GR358c: Layout will cause: BN to PD space >= 0.340 um.
4291 0 GR358d: Layout will cause: PH width >= 0.440 um.
4292 0 GR358e: Layout will cause: BN width >= 0.340 um.
4294 0 GR358f: Layout will cause: BN space >= 0.340 um.
4296 0 GR358f: Layout will cause: BN notch >= 0.340 um.
4297 0 GR358g: Layout will cause: BF width >= 0.980 um.
4299 0 GR358h: Layout will cause: BF space (not over GRLOGIC) >= 1.000 um.
4301 0 GR358h: Layout will cause: BF notch (not over GRLOGIC) >= 1.000 um.
4303 0 GR358i: Layout will cause: PH space >= 0.440 um.
4305 0 GR358i: Layout will cause: PH notch >= 0.440 um.
4306 0 GR358j: Layout will cause: DE width >= 0.440 um.
4308 0 GR358k: Layout will cause: DE space >= 0.440 um.
4310 0 GR358k: Layout will cause: DE notch >= 0.440 um.
4311 0 GR358m: Layout will cause: DF width >= 0.440 um.
4313 0 GR358n: Layout will cause: DF space >= 0.440 um.
4315 0 GR358n: Layout will cause: DF notch >= 0.440 um.
4317 0 GR370: (PC over RX) to BP space >= 0.360 um.
4322 0 GR370: (PC over RX) to BP space (gate end)>= 0.360 um.
4323 0 GR370b: (PC over RX) touching PD found!
4324 0 GR370a: (PC over RX) to BB space >= 0.500 um.
4325 0 GR370b: (PC over RX) to PD >= 0.500 um.
4326 0 GR371: (PC over RX) straddling BP found!
4328 0 GR371: (PC over RX) within BP >= 0.360 um.
4329 0 GRBP3: BP touching BB found!
4333 0 GR372: (BP overlap of RX) not over NW >= 0.220 um.
4334 0 GR372a: Substrate contact area >= 0.147 sq.um.
4337 0 GR373: (RX overlap past BP) over NW  >= 0.220 um.
4338 0 GR373a: Well contact area >= 0.147 sq.um.
4339 0 GR374: RX straddling NW (butted n-well cont) found!
4341 0 GR374: RX within NW (butted n-well cont) >= 0.120 um.
4344 0 GR378: (BP inter RX) to adj ((PC intersect RX) not in BP) >= 0.280 um.
4347 0 GR379: (BP inter RX) overlap past ((PC intersect RX) in BP) >= 0.280 um.
4353 0 GR380: DI must be within BP == 0.040 um. (error >)
4354 0 GR380: DI outside of BP found.
4355 0 GR380a: NW(touching DI) touching JD found!
4356 0 GR380c: NW(touching DI) touching BB found!
4357 0 GR380c: NW(touching DI) touching PI found!
4358 0 GR380d: NW(touching DI) touching RP found!
4359 0 GR380d: NW(touching DI) touching RR found!
4360 0 GR380e: NW(touching DI) touching DG found!
4361 0 GR380e: NW(touching DI) touching OP found!
4362 0 GR380e: NW(touching DI) touching PC found!
4364 0 GR380g: BP(touching DI) touching PD found!
4366 0 GR380: DI must be within BP == 0.040 um. (error <)
4367 0 GR380a: NW(touching DI) to JD space >= 5.000 um.
4368 0 GR380d: NW(touching DI) to RP space >= 2.500 um.
4369 0 GR380d: NW(touching DI) to RR space >= 2.500 um.
4371 0 GR381: RX straddling DI found!
4375 0 GR381b: RX within DI <= 0.340 um.
4377 0 GR381: RX within DI >= 0.100 um.
4384 0 GR382: RX(NWcont) to DI space <= 0.540 um.
4385 0 GR382: DI not within an RX(NWcont) hole found!
4387 0 GR383: DI not enclosing an RX shape found!
4397 0 GR385a: RX(not GRLOGIC) width (max) (when RX touches DI) <= 2.000 um.
4398 0 GR385: RX width (min) (when RX touches DI) >= 1.000 um.
4399 0 GR387: RX(touching DI) not within NW found!
4407 0 GR387b: NW(touching DI) to RX(sxcont) space <= 1.000 um.
4409 0 GR388: (RX(NWcont) over NW(touching DI)) to BP space >= 0.140 um.
4418 0 GR389: (RX(sxcont) over (NW(touch DI) +1.0)) within BP >= 0.140 um.
4426 0 GR710: (OP intersect RX) length >= 0.480 um.
4427 0 GR711: (OP intersect RX) width >= 0.280 um.
4431 0 GR712: (OP intersect PC) length >= 1.060 um.
4432 0 GR713: (OP intersect PC) width >= 0.280 um.
4435 0 GR715a: ((RX touching OP) outside BP) touching NW found!
4436 0 GR715b: ((RX touching OP) inside BP) not within NW found!
4437 0 GR715f: RX(over OP) touching BB found!
4438 0 GR715a: ((RX touching OP) outside BP) to NW space >= 0.420 um.
4440 0 GR715b: ((RX touching OP) inside BP) within NW >= 0.420 um.
4441 0 GR716a: (RX touching OP) straddling NW found!
4442 0 GR716a: (RX touching OP) straddling BB found!
4444 0 GR716b: ((OP intersect RX) touching NW ) not touching BP found!
4446 0 GR716c: ((OP intersect RX) not touching NW ) touching BP found!
4447 0 GR717b: (PC intersect OP) straddling NW found!
4448 0 GR717a: (PC intersect OP) to NW space >= 0.600 um.
4450 0 GR717b: (PC intersect OP) within NW >= 0.860 um.
4451 0 GR725: OP width >= 0.480 um.
4453 0 GR726: OP space >= 0.480 um.
4455 0 GR726: OP notch >= 0.480 um.
4457 0 GR727: OP overlap past RX >= 0.180 um.
4458 0 GR728: OP to RX space >= 0.160 um.
4462 0 GR729a: OP area >= 0.720 sq.um.
4463 0 GR729b: OP enclosed area >= 0.720 sq.um.
4465 0 GR730: OP overlap past PC >= 0.200 um.
4466 0 GR731: OP to PC space>= 0.260 um.
4479 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error >)
4488 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error >)
4489 0 GROP9: OP to adjacent PD >= 0.440 um.
4490 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error <)
4491 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error <)
4492 0 GR732: CA/CABAR over OP found!
4493 0 GR733: CA to OP space >= 0.180 um.
4494 0 GR733a: CABAR to OP space >= 0.360 um.
4495 0 GR734a: (RX touching OP) straddling BP found!
4497 0 GR734a: (RX touching OP) within BP >= 0.220 um.
4498 0 GR734b: (RX touching OP) to BP space >= 0.220 um.
4500 0 GR735a2: (PC touching OP) not within {BP or BB} found!
4502 0 GR735a2: (PC touching OP) within BP >= 0.300 um.
4504 0 GR735a2: (PC touching OP) within BB >= 0.300 um.
4505 0 GR735b: (PC touching OP) to BP space >= 0.300 um.
4506 0 GR736: OP over (PC intersect RX) found!
4509 0 GR736a: RX(touching OP) touching PC found!
4511 0 GR736a1: (RX(touching OP) not touching PC) touching SBLK found!
4512 0 GR736a2: PC(touching OP) touching SBLK found!
4515 0 GR737: OP touching DG found!
4517 0 GR737a: PC(touching OP) touching DG found!
4519 0 GR738: Non-rectangular (OP intersect RX) found!
4521 0 GR738: Non-rectangular (OP intersect PC) found!
4523 0 GR739a: RX overlap past OP >= 0.620 um.
4525 0 GR739b: PC overlap past OP >= 0.580 um.
4526 0 GROP20: OP to adjacent RN >= 0.600 um.
4528 0 GROP24: OP touching RX(over RN) found!
4529 0 GROP29: PC(touching OP) touching RX found!
4531 0 GROP30: ((PC over OP) over NW) to RX space >= 0.380 um.
4532 0 GROP31: (PC touching OP) to RN must be>= 0.3um !
4543 0 GROP31: (PC touching OP) cannot touch RN !
4547 0 GROP32: ((RX over OP) not over GRLOGIC)) to (NR or PR) space >= 0.260 um.
4548 0 GROP32: ((RX over OP) not over GRLOGIC)) touching (NR or PR) found!
4559 0 GRPCR20a: (PCtouching OP) touching NS found !
4560 0 GRPBR19: More than ONE set of contacts found on a PC resistor!
4562 0 GRPBR19: More than ONE set of contacts found on a RX resistor!
4565 0 GRPBR29: PC(touching OP, not GRLOGIC) within NW >= 2.000 um.
4568 0 GRPBR31: PC(touching OP, touching BB) within BB >= 2.000 um.
4571 0 GRPBR33: PC(touch OP, no touch NW, not GRLOGIC) to adjacent NW >= 2.000 um.
4573 0 GRPBR35: PC(touching OP, not touching BB) to adjacent BB >= 2.000 um.
4574 0 GRRR1: RR width >= 0.800 um.
4576 0 GRRR2: RR space >= 0.800 um.
4578 0 GRRR2: RR notch >= 0.800 um.
4579 0 GRRR3: RR touching RP found!
4580 0 GRRR3: RR to RP space >= 0.800 um.
4581 0 GRRR4: PC straddling RR found!
4583 0 GRRR4: PC within RR >= 0.260 um.
4584 0 GRRR5: RR to adjacent PC >= 0.280 um.
4585 0 GRRR6: RR to (PC over RX) space >= 0.500 um.
4586 0 GRRR7: RR touching RX found!
4587 0 GRRR7: RR to adjacent RX >= 0.280 um.
4589 0 GRRR8: BP within RR >= 0.000 um.
4591 0 GRRR9: BP(touching RR) touching BB found!
4593 0 GRRR9: BP(touching RR) touching PC(not touching RR) found!
4595 0 GRRR10: PC(not touching OP) touching RR found!
4597 0 GRRR11: (CA/CABAR over RR) not covered by PD found!
4598 0 GRRP1: RP width >= 0.800 um.
4600 0 GRRP2: RP space >= 0.800 um.
4602 0 GRRP2: RP notch >= 0.800 um.
4603 0 GRRP4: PC straddling RP found!
4605 0 GRRP4: PC within RP >= 0.260 um.
4606 0 GRRP5: RP to adjacent PC >= 0.280 um.
4607 0 GRRP6: RP to (PC over RX) space >= 0.500 um.
4608 0 GRRP7: RP touching RX found!
4609 0 GRRP7: RP to adjacent RX >= 0.280 um.
4611 0 GRRP8: BP within RP >= 0.000 um.
4613 0 GRRP9: BP(touching RP) touching BB found!
4615 0 GRRP9: BP(touching RP) touching PC(not touching RP) found!
4617 0 GRRP10: PC(not touching OP) touching RP found!
4619 0 GRRP11: (CA/CABAR over RP) not covered by PD found!
4620 0 GRKX1: K1 width (min) >= 5.000 um.
4621 0 GRKX2: V1 straddling K1 found!
4623 0 GRKX2: V1 within K1 >= 0.5000 um.
4625 0 GRKX3: K1 space >= 5.500 um.
4626 0 GRKX4: K1 touching M1 found!
4627 0 GRKX4: K1 to M1 space >= 1.000 um.
4638 0 GRKX5: More than ONE set of contacts found on a K1 resistor!
4651 0 GRKX6: K1 width (max) <= 30.000 um.
4653 0 GRKX8: Non-rectangular K1 found!
4654 0 GRKX8: 45 degree K1 found!
4665 0 GRKX9: V1(touching K1) space == 0.28 um. (error >)
4673 0 GRKX10: K1/M2 intersection only enclosing one V1 shape found!
4675 0 GRKX10: K1/MT intersection only enclosing one V1 shape found!
4676 0 GRKX11: K1 touching OP found!
4681 0 GRDG0: DGV must be within DG == 0.000 um.
4682 0 GRDG1: Non-orthagonal DG found!
4686 0 GRDG2b: Non-rectangular ((PC over RX) over DG) found!
4687 0 GRDG2b: 45 degree ((PC over RX) over DG) found!
4689 0 GRDG3: (PC touching DG) to RX space >= 0.080 um.
4690 0 GRDG4: (PC over RX) straddling DG found!
4692 0 GRDG4: (PC over RX) within DG >= 0.500 um.
4693 0 GRDG5: (PC over RX) to DG space >= 0.500 um.
4694 0 GRDG6: DG width >= 0.440 um.
4696 0 GRDG7: DG space >= 0.440 um.
4698 0 GRDG7: DG notch >= 0.440 um.
4701 0 GRDG8a/b: (((PC over RX) over DG) not over DGV) width >= 0.400 um.
4702 0 GRDGV8a/b: (((PC over RX) over DG) over DGV) width >= 0.320 um.
4704 0 GRDG8c: ((PC over RX) over DG) space >= 0.300 um.
4705 0 GRDG8d: (CA over RX) to adj ((PC over RX) over DG) space >= 0.200 um.
4707 0 GRDG9: DG overlap past NW >= 0.440 um.
4708 0 GRDG10 : DG to NR >= 0.700 um.
4709 0 GRDG10 : DG touching NR found!
4710 0 GRDG11 : DG to PR >= 0.700 um.
4711 0 GRDG11 : DG touching PR found!
4712 0 GRDG13: DG to NW space >= 0.440 um.
4713 0 GRDG13: DG to BB space >= 0.440 um.
4714 0 GRDG13: DG to BH space >= 0.440 um.
4715 0 GRDG13: Layout will cause: DG to BH space >= 0.440 um.
4716 0 GRDG14: DG overlap of NW >= 0.440 um.
4717 0 GRDG15: DG to (OP intersect PC) space >= 0.700 um.
4719 0 GRDG16: NW overlap past DG >= 0.440 um.
4720 0 GRDG21: DG touching BB found!
4725 0 GRDG50: ((RX over PC) over DG) width >= 0.500 um.
4726 0 GRDG52: (RX touching DG) to RX space >= 0.380 um.
4731 0 GRDG110: (RX over DG) overlap past PC >= 0.380 um.
4734 0 GRDG260: (RX(P+) touching DG) within NW >= 0.560 um.
4737 0 GRDG265a: (RX(N+) touching DG) to adjacent NW >= 0.560 um.
4738 0 GRDG265a1: (RX(N+) touching DG) to adjacent BB >= 0.560 um.
4739 0 GRDG265b: RX(N+) to adjacent (NW touching DG) >= 0.560 um.
4741 0 GRDG268: (RX(in BP)touch DG) to RX(not BP) (same NW) space <= 20.000 um.
4744 0 GRDG268b: (RX(no BP)touch DG) to Substrate Contact space <= 20.000 um.
4745 0 GRPD1: PD width >= 0.340 um.
4747 0 GRPD2: PD space >= 0.340 um.
4749 0 GRPD2: PD notch >= 0.340 um.
4751 0 GRPD3: PDHOLE width (for SBD anode) >= 2.000 um.
4757 0 GRPD4: PD to adj (RX not within PC(+0.22)) >= 0.360 um.
4759 0 GRPD5: RX intersect PD (SBD guardring) >= 0.320 um.
4761 0 GRPD6: RX(not over SBD) straddling PD found!
4764 0 GRPD6: RX(not over SBD) within PD >= 0.200 um.
4766 0 GRPD6a: PD overlap past RX(SBD guardring) >= 0.360 um.
4768 0 GRPD7: PD overlap past PC >= 0.280 um.
4769 0 GRPD9b: Non-orthogonal PD shape found!
4770 0 GRPD10a: PD to adjacent PC >= 0.280 um.
4771 0 GRPD11: PD enclosed area >= 0.320 sq.um.
4774 0 GRPD14: CA(not over RN) not within PD(SBD) found!
4776 0 GRPD14: CA(not over RN) must be within PD(SBD) >= 0.280 um.
4778 0 GRPD15: (RX touching PD(touching SBD)) touching BP(drawn) found!
4781 0 GRPD16: PD(touching SBD) touching {PC or (RX not touching PD)} found!
4782 0 GRRN1: RN width >= 0.800 um.
4784 0 GRRN2: RN space >= 1.280 um.
4786 0 GRRN2: RN notch >= 1.280 um.
4787 0 GRRN3: RN to adjacent RX >= 0.420 um.
4788 0 GRRN4: RX straddling RN found!
4790 0 GRRN4: RX within RN >= 0.140 um.
4792 0 GRRN5a: (RX within RN) touching BP found!
4794 0 GRRN6: RN touching a P+ Junction found!
4795 0 GRRN7: RN touching a Substrate Contact found!
4799 0 GRRN9: RN enclosed area >= 0.537 sq.um.
4800 0 GRRN10: (RN over RX) touching PD found!
4801 0 GRRN11: RN not within NS found!
4802 0 GRRN12: RN to NW space >= 1.280 um.
4804 0 GRRN13: (RN union NW) width >= 0.700 um.
4805 0 GRNS1: NS width >= 4.500 um.
4807 0 GRNS2: NS space >= 3.680 um.
4809 0 GRNS2: NS notch >= 3.680 um.
4810 0 GRNS4b: NS touching NW found!
4811 0 GRNS5: NS to adjacent NW space >= 3.680 um.
4816 0 GRCPNS7: NS within BB == 2.100 um.(error >)
4818 0 GRCPNS7: NS within BB == 2.100 um.(error <)
4819 0 GRNS9: NS not covered by BB found!
4820 0 GRNS10: NS to adjacent BB >= 5.200 um.
4822 0 GRNS15a: More than one (RX union NS) shape in the same BB found!
4824 0 GRNS16: NS not enclosing RX(over RN) found!
4826 0 GRNS21b: NS touching ((RX touching PD) not over SBD) found!
4828 0 GRNS21b: NS touching ((RX touching BP) not over SBD)found!
4829 0 GRNS21b: NS to (RX touching PD) space >= 2.760 um.
4830 0 GRNS21b: NS to (RX touching BP) space >= 2.760 um.
4832 0 GRNS26: NS not touching (JD (HAVAR) or PD hole (SBD)) found!
4843 0 GRBB1a: BB(abutting NW) width == 1.000 um.(error >)
4844 0 GRBB1: BB(not abutting NW) width >= 2.760 um.
4845 0 GRBB1a: BB(abutting NW) width == 1.000 um.(error <)
4847 0 GRBB2: BB space >= 2.00 um.
4849 0 GRBB2: BB notch >= 2.00 um.
4850 0 GRBB6: BB area >= 9.600 sq.um.
4854 0 GRBB7: BB enclosed area >= 4.000 sq.um.
4855 0 GRBB34: BB over NW found!
4858 0 GRBB34a: BB touching more than one (union(union(NS, NW), RN)) shapes not allowed !
4859 0 GRBB35a: BB touching BP found!
4860 0 GRBB35: BB to adjacent BP >= 0.440 um.
4879 0 GRBB37: PD not within {[BB touch IND_FLT] or [(BP or BB) over (PC(res)+ 0.40)] or SBD} found!
4882 0 GRBB38: ((RX touching BB), not over IND_FLT) not touching NS found!
4883 0 GRBB41: PC straddling BB found!
4885 0 GRBB41: PC within BB >= 0.500 um.
4890 0 GRPBN10: PC(touching PD) not within {BP or BB} found!
4891 0 GRPBN10: PC(touching RR) not within {BP or BB} found!
4892 0 GRPBN10: PC(touching RP) not within {BP or BB} found!
4894 0 GRPBN10: PC(touch PD) must be within {BP or BB} >= 0.400 um.
4896 0 GRPBN10: PC(touch RR) must be within {BP or BB} >= 0.400 um.
4898 0 GRPBN10: PC(touch RP) must be within {BP or BB} >= 0.400 um.
4903 0 GRPBN11: (PC(touching CA/CABAR) intersect BB) not within {PD/RR/RP} found!
4904 0 GRPBN12: PC to adjacent BB space >= 0.320 um.
4905 0 GRTW01a: Non-orthagonal PI found!
4906 0 GRTW01: PI width >= 3.20 um.
4908 0 GRTW02: PI space >= 4.00 um.
4910 0 GRTW02: PI notch >= 4.00 um.
4911 0 GRTW03: PI touching RN found!
4912 0 GRTW03: PI touching NR found!
4913 0 GRTW03: PI touching PR found!
4914 0 GRTW03: PI touching DI found!
4915 0 GRTW03: PI touching PD found!
4921 0 GRTW04: PI(edge) not covered by NW found!
4922 0 GRTW05: PI overlap of NW >= 1.00 um.
4924 0 GRTW06: NW overlap past PI >= 1.10 um.
4925 0 GRTW10a1: PI touching BB found!
4926 0 GRTW10a: PI touching NS found!
4929 0 GRTW10: (PI to adjacent BB) not over NW >= 3.20 um.
4930 0 GRTW10a: PI to adjacent NS >= 5.52 um.
4933 0 GRTW10a1: (PI to adjacent BB) over NW >= 1.10 um.
4935 0 GRTW17a: (((RX over BP) over VTSENS) over NW) to PI space >= 1.000 um.
4936 0 GRTW18: PI to NW space >= 3.200 um.
4938 0 GRTW19: PI(not over NW) not touching a Pwell contact found!
4940 0 GRTW260: ((RX over BP) over NW) to (PI not over NW) space >= 0.420 um.
4945 0 GRTW265: (RX(not over BP) over PI) to adjacent (NW touching PI) >= 0.80 um.
4946 0 GRTW265a: ((RX(not over BP) touch DG) over PI) to adjacent (NW touching PI) >= 0.96 um.
4948 0 GRTW266: (RX(over BP) not over PI) to (NW touching PI) space >= 0.160 um.
4953 0 GR1a: (Gate over ZEROVT) width >= 0.70 um.
4955 0 GR1b: (RX touching ZEROVT) touching DG found!
4967 0 GR10a: ((RX under PC) touching ZEROVT) width >= 3.00 um.
4970 0 GR122: Polygonal (PC over RX) (bent gates) over ZEROVT found!
4971 0 GR280a: Non-orthagonal ZEROVT shapes found!
4972 0 GR280: ZEROVT width >= 2.40 um.
4974 0 GR282: ZEROVT space >= 1.88 um.
4976 0 GR282: ZEROVT notch >= 1.88 um.
4977 0 GR283: ZEROVT touching more than one RX shape found!
4978 0 GR284: ZEROVT not within RX found!
4983 0 GR284: ZEROVT must be within RX == 0.30 um. (error >)
4985 0 GR284: ZEROVT must be within RX == 0.30 um. (error <)
4986 0 GR286: BP touching ZEROVT found!
4987 0 GR288: ZEROVT to adjacent RX >= 1.30 um.
4988 0 GR289: ZEROVT touching NW found!
4989 0 GR289a: ZEROVT touching BB found!
4990 0 GR289: ZEROVT to NW space >= 1.66 um.
4991 0 GR289a: ZEROVT to BB space >= 1.90 um.
4993 0 GRZT1: ZEROVT overlap past (PC over RX) >= 0.92 um.
5012 0 GRZT2: ZEROVT vertices over (PC over RX) found!
5013 0 GRZT3: ZEROVT to adjacent DG >= 1.20 um.
5014 0 GRZT4: ZEROVT to adjacent (PC under OP) >= 1.32 um.
5015 0 GRZT5: ZEROVT touching JD found!
5016 0 GRZT5: ZEROVT touching RP found!
5017 0 GRZT5: ZEROVT touching RR found!
5018 0 GRZT5: ZEROVT to JD space >= 1.66 um.
5019 0 GRZT5: ZEROVT to RP space >= 1.66 um.
5020 0 GRZT5: ZEROVT to RR space >= 1.66 um.
5021 0 GRZT6: ZEROVT touching PI found!
5022 0 GRZT6: ZEROVT to PI space >= 3.00 um.
5023 0 GR790: BFMOAT width >= 10.000 um.
5024 0 GR792: BB to adjacent BFMOAT space >= 10.000 um.
5026 0 GR792: BFMOAT space >= 10.000 um.
5028 0 GR792: BFMOAT notch >= 10.000 um.
5029 0 GR793: BFMOAT to adjacent NW space >= 2.000 um.
5030 0 GR795: BFMOAT to adjacent RX space >= 1.000 um.
5031 0 GR799: BB touching BFMOAT found!
5032 0 GR799: NW touching BFMOAT found!
5033 0 GR799: PC touching BFMOAT found!
5034 0 GR799: RX touching BFMOAT found!
5035 0 GR799: NS touching BFMOAT found!
5036 0 GR799: NR touching BFMOAT found!
5037 0 GR799: PR touching BFMOAT found!
5495 0 GR500b: M1 width (max) <= 35.000 um.
5496 0 GR500: M1 width (min) >= 0.240 um.
5500 0 GR501a: M1 area >= 0.172 sq.um.
5501 0 GR501b: M1 enclosed area >= 0.705 sq. um.
5503 0 GR502: M1 space >= 0.200 um.
5505 0 GR502: M1 notch >= 0.200 um.
5508 0 GR504: M1(>1.48) to M1 space (run <= 0) >= 0.320 um.
5511 0 GR504: M1(>1.48) to M1(<=1.48) space (run < 0) >= 0.320 um.
5515 0 GR504: M1(>1.48) to M1(>1.48) space >= 0.320 um.
5519 0 GR504: M1(>1.48) notch >= 0.320 um.
5523 0 GR504a: M1(>1.60) to M1 space (run <= 0) >= 0.360 um.
5527 0 GR504a: M1(>1.60) to M1(<=1.60) space (run < 0) >= 0.360 um.
5532 0 GR504a: M1(>1.60) to M1(>1.60) space >= 0.360 um.
5537 0 GR504a: M1(>1.60) notch >= 0.360 um.
5540 0 GR504b: M1(>4.00) to M1 space (run <= 0) >= 0.600 um.
5543 0 GR504b: M1(>4.00) to M1(<=4.00) space (run < 0) >= 0.600 um.
5547 0 GR504b: M1(>4.00) to M1(>4.00) space (run < 0) >= 0.600 um.
5551 0 GR504b: M1(>4.00) notch >= 0.600 um.
5552 0 GR505a: CA not within M1 found!
5553 0 GR505b: CABAR not within M1 found!
5555 0 GR505a: CA must be within M1 >= 0.020 um.
5557 0 GR505b: CABAR must be within M1 >= 0.040 um.
5558 0 GR550: V1 width and length == 0.280 um. (error <)
5559 0 GR550: V2 width and length == 0.280 um. (error <)
5560 0 GR550: V3 width and length == 0.280 um. (error <)
5561 0 GR550: V4 width and length == 0.280 um. (error <)
5562 0 GR550: V5 width and length == 0.280 um. (error <)
5563 0 GR550: V1 width and length == 0.280 um. (error >)
5564 0 GR550: V2 width and length == 0.280 um. (error >)
5565 0 GR550: V3 width and length == 0.280 um. (error >)
5566 0 GR550: V4 width and length == 0.280 um. (error >)
5567 0 GR550: V5 width and length == 0.280 um. (error >)
5569 0 GR553a: V1 to V1 space >= 0.280 um.
5571 0 GR553a: V2 to V2 space >= 0.280 um.
5573 0 GR553a: V3 to V3 space >= 0.280 um.
5575 0 GR553a: V4 to V4 space >= 0.280 um.
5577 0 GR553a: V5 to V5 space >= 0.280 um.
5579 0 GR557: Non-rectangular V1 found!
5581 0 GR557: Non-rectangular V2 found!
5583 0 GR557: Non-rectangular V3 found!
5585 0 GR557: Non-rectangular V4 found!
5587 0 GR557: Non-rectangular V5 found!
5588 0 GR557: 45 degree V1 found!
5589 0 GR557: 45 degree V2 found!
5590 0 GR557: 45 degree V3 found!
5591 0 GR557: 45 degree V4 found!
5592 0 GR557: 45 degree V5 found!
5593 0 GR558: V1BAR outside of Chipring found!
5594 0 GR558: V2BAR outside of Chipring found!
5595 0 GR558: V3BAR outside of Chipring found!
5596 0 GR558: V4BAR outside of Chipring found!
5597 0 GR558: V5BAR outside of Chipring found!
5598 0 GR566: V1 overlapping V1BAR found!
5599 0 GR566: V2 overlapping V2BAR found!
5600 0 GR566: V3 overlapping V3BAR found!
5601 0 GR566: V4 overlapping V4BAR found!
5602 0 GR566: V5 overlapping V5BAR found!
5603 0 GR566: V1BAR to V1 space >= 0.560 um.
5604 0 GR566: V2BAR to V2 space >= 0.560 um.
5605 0 GR566: V3BAR to V3 space >= 0.560 um.
5606 0 GR566: V4BAR to V4 space >= 0.560 um.
5607 0 GR566: V5BAR to V5 space >= 0.560 um.
5615 0 GR570: V1(not over K1) must be within M1 >= -0.020 um.
5617 0 GR575: V1 not within M2 found!
5619 0 GR575a1: V1 not within MT found!
5620 0 GR600: M2 width (min) >= 0.280 um.
5621 0 GR600: M3 width (min) >= 0.280 um.
5622 0 GR600: M4 width (min) >= 0.280 um.
5623 0 GR600: M5 width (min) >= 0.280 um.
5636 0 GR601a: M2 area > 0.3136 sq.um.
5637 0 GR601a: M3 area > 0.3136 sq.um.
5638 0 GR601a: M4 area > 0.3136 sq.um.
5639 0 GR601a: M5 area > 0.3136 sq.um.
5640 0 GR601b: M2 enclosed area >= 0.705 sq.um.
5641 0 GR601b: M3 enclosed area >= 0.705 sq.um.
5642 0 GR601b: M4 enclosed area >= 0.705 sq.um.
5643 0 GR601b: M5 enclosed area >= 0.705 sq.um.
5645 0 GR602: M2 space >= 0.280 um.
5647 0 GR602: M2 notch >= 0.280 um.
5649 0 GR602: M3 space >= 0.280 um.
5651 0 GR602: M3 notch >= 0.280 um.
5653 0 GR602: M4 space >= 0.280 um.
5655 0 GR602: M4 notch >= 0.280 um.
5657 0 GR602: M5 space >= 0.280 um.
5659 0 GR602: M5 notch >= 0.280 um.
5663 0 GR604: M2(>1.60) to M2(>=1.60) space (run >= 0) >= 0.400 um.
5667 0 GR604: M2(>1.60) to M2(>=1.60) space (run < 0) >= 0.400 um.
5671 0 GR604: M2(>1.60) notch >= 0.400 um.
5675 0 GR604: M3(>1.60) to M3(>=1.60) space (run >= 0) >= 0.400 um.
5679 0 GR604: M3(>1.60) to M3(>=1.60) space (run < 0) >= 0.400 um.
5683 0 GR604: M3(>1.60) notch >= 0.400 um.
5687 0 GR604: M4(>1.60) to M4(>=1.60) space (run >= 0) >= 0.400 um.
5691 0 GR604: M4(>1.60) to M4(>=1.60) space (run < 0) >= 0.400 um.
5695 0 GR604: M4(>1.60) notch >= 0.400 um.
5699 0 GR604: M5(>1.60) to M5(>=1.60) space (run >= 0) >= 0.400 um.
5703 0 GR604: M5(>1.60) to M5(>=1.60) space (run < 0) >= 0.400 um.
5707 0 GR604: M5(>1.60) notch >= 0.400 um.
5710 0 GR604a: M2(>5.00) to M2 space (run >= 0) >= 0.600 um.
5713 0 GR604a: M2(>5.00) to M2(<=5.00) space (run < 0) >= 0.600 um.
5717 0 GR604a: M2(>5.00) to M2(>5.00) space (run < 0) >= 0.600 um.
5721 0 GR604a: M2(>5.00) notch  >= 0.600 um.
5724 0 GR604a: M3(>5.00) to M3 space (run >= 0) >= 0.600 um.
5727 0 GR604a: M3(>5.00) to M3(<=5.00) space (run < 0) >= 0.600 um.
5731 0 GR604a: M3(>5.00) to M3(>5.00) space (run < 0) >= 0.600 um.
5735 0 GR604a: M3(>5.00) notch  >= 0.600 um.
5738 0 GR604a: M4(>5.00) to M4 space (run >= 0) >= 0.600 um.
5741 0 GR604a: M4(>5.00) to M4(<=5.00) space (run < 0) >= 0.600 um.
5745 0 GR604a: M4(>5.00) to M4(>5.00) space (run < 0) >= 0.600 um.
5749 0 GR604a: M4(>5.00) notch  >= 0.600 um.
5752 0 GR604a: M5(>5.00) to M5 space (run >= 0) >= 0.600 um.
5755 0 GR604a: M5(>5.00) to M5(<=5.00) space (run < 0) >= 0.600 um.
5759 0 GR604a: M5(>5.00) to M5(>5.00) space (run < 0) >= 0.600 um.
5763 0 GR604a: M5(>5.00) notch  >= 0.600 um.
5764 0 GR610: V2 not within M2 found!
5765 0 GR610: V3 not within M3 found!
5766 0 GR610: V4 not within M4 found!
5767 0 GR610: V5 not within M5 found!
5769 0 GR611: V2 not within M3 found!
5771 0 GR611: V2 not within MT found!
5773 0 GR611: V3 not within M4 found!
5775 0 GR611: V3 not within MT found!
5777 0 GR611: V4 not within M5 found!
5779 0 GR611: V4 not within MT found!
5781 0 GR611: V5 not within MT found!
5793 0 GR612: M1/M2 intersection only enclosing one V1 shape found!
5795 0 GR612: M1/MT intersection only enclosing one V1 shape found!
5796 0 GR640: MT width >= 0.280 um.
5800 0 GR641a: MT area > 0.548 sq.um.
5801 0 GR641b: MT enclosed area >= 0.705 sq.um.
5803 0 GR642: MT space >= 0.280 um.
5805 0 GR642: MT notch >= 0.280 um.
5808 0 GR644: MT(>1.60) to MT space (run >= 0) >= 0.400 um.
5811 0 GR644: MT(>1.60) to MT(<=1.60) space (run < 0) >= 0.400 um.
5815 0 GR644: MT(>1.60) to MT(>=1.60) space (run < 0) >= 0.400 um.
5819 0 GR644: MT(>1.60) notch >= 0.400 um.
5822 0 GR644a: MT(>5.00) to MT space (run >= 0) >= 0.600 um.
5825 0 GR644a: MT(>5.00) to MT(<=5.00) space (run < 0) >= 0.600 um.
5829 0 GR644a: MT(>5.00) to MT(>=5.00) space (run < 0) >= 0.600 um.
5833 0 GR644a: MT(>5.00) notch >= 0.600 um.
5836 0 GR644b: MT(>35.00) to MT space (run <= 0) >= 2.000 um.
5839 0 GR644b: MT(>35.00) to MT(<=35.00) space (run < 0) >= 2.000 um.
5843 0 GR644b: MT(>35.00) to MT(>=35.00) space (run < 0) >= 2.000 um.
5847 0 GR644b: MT(>35.00) notch >= 2.000 um.
5848 0 GR650a: LV width >= 14.000 um.
5849 0 GR650b: DV width >= 14.000 um.
5850 0 GR651a: LV area >= 550.000 sq.um.
5851 0 GR651b: DV area >= 480.000 sq.um.
5853 0 GR653b: DV space >= 11.000 um.
5855 0 GR653b: DV notch >= 11.000 um.
5857 0 GR653c: LV space >= 29.000 um.
5859 0 GR653c: LV notch >= 29.000 um.
5861 0 GR658c: DV within CHIPEDGE >= 20.000 um.
5863 0 GR658d: LV within CHIPEDGE >= 29.000 um.
5864 0 ERROR: C4LV SHAPES FOUND! - PLEASE PICK A C4 SWITCH AND RERUN THE DRC CHECK
5865 0 GRBEOL1: C4LV touching DV found!
5875 0 GRA500b: M1(over M1CHEXCL) width (max) <= 14.000 um.
5912 0 GRA504a: M1(over M1CHEXCL) space (if one line > 2.40 wide) >= 0.700 um.
5913 0 GRA504b: M1(over M1CHEXCL) space (if one line > 5.30 wide) >= 1.600 um.
5914 0 GRA504c: M1(over M1CHEXCL) space (if one line > 8.40 wide) >= 2.500 um.
5915 0 GRA504d: M1(over M1CHEXCL) space (if one line >11.50 wide) >= 3.500 um.
5917 0 GRA504a: M1(over M1CHEXCL) notch (if one line > 2.40 wide) >= 0.700 um.
5919 0 GRA504b: M1(over M1CHEXCL) notch (if one line > 5.30 wide) >= 1.600 um.
5921 0 GRA504c: M1(over M1CHEXCL) notch (if one line > 8.40 wide) >= 2.500 um.
5923 0 GRA504d: M1(over M1CHEXCL) notch (if one line >11.50 wide) >= 3.500 um.
5924 0 GRJD1: JD width >= 1.000 um.
5926 0 GRJD2: JD space >= 1.000 um.
5928 0 GRJD2: JD notch >= 1.000 um.
5929 0 GRJD3: RX straddling JD found!
5931 0 GRJD3: RX within JD >= 0.320 um.
5932 0 GRJD4: JD to PC space >= 1.040 um.
5933 0 GRJD4a: JD to RX space >= 0.580 um.
5934 0 GRJD5: JD touching OP found!
5935 0 GRJD5: JD touching PC found!
5936 0 GRJD5: JD touching RN found!
5937 0 GRJD5: JD touching RP found!
5938 0 GRJD5: JD touching RR found!
5940 0 GRJD6: JD touching (RX not touching NS) found!
5941 0 GRMOSVAR1: MOSVAR width >= 0.440 um.
5943 0 GRMOSVAR2: MOSVAR space >= 0.440 um.
5945 0 GRMOSVAR2: MOSVAR notch >= 0.440 um.
5946 0 GRMOSVAR3: MOSVAR touching BP found!
5947 0 GRMOSVAR3: MOSVAR touching DG found!
5948 0 GRMOSVAR3: MOSVAR touching NS found!
5949 0 GRMOSVAR3: MOSVAR touching RP found!
5950 0 GRMOSVAR3: MOSVAR touching RR found!
5951 0 GRMOSVAR4: MOSVAR to BB space >= 0.440 um.
5952 0 GRMOSVAR4: MOSVAR to DG space >= 0.440 um.
5953 0 GRMOSVAR4: MOSVAR to NW space >= 0.440 um.
5954 0 GRMOSVAR5: MOSVAR to RX space >= 0.340 um.
5955 0 GRMOSVAR5a: MOSVAR to (PC over RX) space >= 0.500 um.
5958 0 GRMOSVAR6: (RX touch MOSVAR) not within (NW over MOSVAR) found!
5960 0 GRMOSVAR6: (RX touch MOSVAR) must be within (NW over MOSVAR) >= 0.420 um.
5970 0 GRE1aa: E1(not under IND_FLT) width (max) <= 25.000 um.
5980 0 GRE1ab: E1(under IND_FLT) width (max) <= 30.000 um.
5981 0 GRE1a: E1 width (min) >= 1.500 um.
5983 0 GRE1b: E1 space >= 2.000 um.
5985 0 GRE1b: E1 notch >= 2.000 um.
5987 0 GRE1e: FT not within E1 found!
5989 0 GRE1e: FT must be within E1 >= 1.000 um.
5991 0 GRE1f: FTBAR not within E1 found!
5993 0 GRE1f: FTBAR must be within E1 >= 1.000 um.
5994 0 GRE1g: E1 area >= 6.000 sq.um.
6076 0 GRE1S4:  E1(>17.50) to E1(<=17.50) space (under IND_FLT) >= 5.000 um.
6078 0 GRE1S4:  E1(>17.50) space (under IND_FLT) >= 5.000 um.
6080 0 GRE1S4:  E1(>17.50) notch (under IND_FLT) >= 5.000 um.
6082 0 GRE1S1:  E1 space (if one line >  8.00 wide) >= 2.500 um.
6084 0 GRE1S2:  E1 space (if one line > 11.50 wide) >= 3.500 um.
6086 0 GRE1S3:  E1 space (if one line > 14.00 wide) >= 4.500 um.
6090 0 GRE1S4:  E1 space (if one line > 17.50 wide) >= 5.500 um.
6094 0 GRE1S5:  E1 space (if one line > 21.00 wide) >= 6.500 um.
6098 0 GRE1S6:  E1 space (if one line > 24.50 wide) >= 7.500 um.
6099 0 GRE1S1:  E1 space (if one line >  8.00 wide) >= 2.500 um.(corners)
6100 0 GRE1S2:  E1 space (if one line > 11.50 wide) >= 3.500 um.(corners)
6101 0 GRE1S3:  E1 space (if one line > 14.00 wide) >= 4.500 um.(corners)
6104 0 GRE1S4:  E1 space (if one line > 17.50 wide) >= 5.500 um.(corners)
6107 0 GRE1S5:  E1 space (if one line > 21.00 wide) >= 6.500 um.(corners)
6110 0 GRE1S6:  E1 space (if one line > 24.50 wide) >= 7.500 um.(corners)
6112 0 GRE1S1:  E1 space (if both lines >  8.00 wide) >= 2.500 um.(corners)
6114 0 GRE1S2:  E1 space (if both lines > 11.50 wide) >= 3.500 um.(corners)
6116 0 GRE1S3:  E1 space (if both lines > 14.00 wide) >= 4.500 um.(corners)
6118 0 GRE1S4:  E1 space (if both lines > 17.50 wide) >= 5.500 um.(corners)
6120 0 GRE1S5:  E1 space (if both lines > 21.00 wide) >= 6.500 um.(corners)
6122 0 GRE1S6:  E1 space (if both lines > 24.50 wide) >= 7.500 um.(corners)
6124 0 GRE1S1:  E1 notch (if both lines >  8.00 wide) >= 2.500 um.
6126 0 GRE1S2:  E1 notch (if both lines > 11.50 wide) >= 3.500 um.
6128 0 GRE1S3:  E1 notch (if both lines > 14.00 wide) >= 4.500 um.
6130 0 GRE1S4:  E1 notch (if both lines > 17.50 wide) >= 5.500 um.
6132 0 GRE1S5:  E1 notch (if both lines > 21.00 wide) >= 6.500 um.
6134 0 GRE1S6:  E1 notch (if both lines > 24.50 wide) >= 7.500 um.
6155 0 GRE1A1: E1 enclosed area (if one line >  8.00 wide) >=  19.000 sq. um.
6156 0 GRE1A2: E1 enclosed area (if one line > 11.50 wide) >=  37.000 sq. um.
6157 0 GRE1A3: E1 enclosed area (if one line > 14.00 wide) >=  61.000 sq. um.
6158 0 GRE1A4: E1 enclosed area (if one line > 17.50 wide) >=  91.000 sq. um.
6159 0 GRE1A5: E1 enclosed area (if one line > 21.00 wide) >= 127.000 sq. um.
6160 0 GRE1A6: E1 enclosed area (if one line > 24.50 wide) >= 169.000 sq. um.
6161 0 GRE1A7: E1 enclosed area (if one line > 28.00 wide) >= 217.000 sq. um.
6162 0 GRE2a: E2 width (min) >= 2.000 um.
6164 0 GRE2b: E2 space >= 2.000 um.
6166 0 GRE2b: E2 notch >= 2.000 um.
6167 0 GRE2c: E2 area (min) >= 4.000 sq.um.
6168 0 GRE2d: E2 not within E1 found!
6170 0 GRE2d: E2 must be within E1 >= 0.600 um.
6171 0 GRE2e: E2 not within MA found!
6175 0 GRE2e: E2(not under IND) must be within MA >= 1.760 um.
6177 0 GRE2e: E2(under IND) must be within MA >= 1.760 um.
6185 0 GRE2f: E1/MA intersection only enclosing one small E2 shape found!
6194 0 GRE2f: E1/MA intersection with two small E2's not at minimum pitch found!
6195 0 GRFT1: FT width == 1.24 um.(error <)
6196 0 GRFT1: FT width == 1.24 um.(error >)
6198 0 GRFT2: FT space >= 2.000 um.
6209 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error >)
6218 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error >)
6219 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error <)
6220 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error <)
6221 0 GRFT4: FTBAR length (min) <= 1.260 um.
6222 0 GRFT5: FTBAR length (max) <= 20.000 um.
6223 0 GRFT6: FT touching FTBAR found!
6224 0 GRFT6: FT to FTBAR space >= 2.000 um.
6226 0 GRFT7: FTBAR space (run length <= 5.0) >= 2.000 um.
6228 0 GRFT8: FTBAR space (run length > 5.0) >= 4.000 um.
6229 0 GRFT9: FT not within MT found!
6231 0 GRFT9: FT must be within MT >= 1.000 um.
6232 0 GRFT10: FTBAR not within MT found!
6234 0 GRFT10: FTBAR must be within MT >= 1.000 um.
6239 0 GRFT11: Non-retangular FT/FTBAR found!
6240 0 GRFT12: 45 degree FT found!
6241 0 GRFT12: 45 degree FTBAR found!
6243 0 GRAM1: AM width >= 2.000 um.
6244 0 GRAM1a: AM area >= 10.000 sq.um.
6259 0 GRAM2a: AM space (within (FT/FTBAR not (LOWCRNT, IND_FILT)) +8.0 um.) >= 5.000 um.
6261 0 GRAM2: AM space >= 2.800 um.
6263 0 GRAM2: AM notch >= 2.800 um.
6276 0 GRAM2a: AM space for AM edges (within (FT/FTBAR over IND_FILT) +6.0 um.) >= 5.000 um.
6298 0 GRAM2b: (AM not under IND_FILT) space (if at least one metal line is greater than 10um wide) >= 4.00um !
6299 0 GRAM2b: (AM not under IND_FILT) space (if at least one metal line is greater than 10um wide) >= 4.00um !
6302 0 GRAM2c: AM(>50.00) to AM space (run <= 0) >= 5.000 um.
6305 0 GRAM2c: AM(>50.00) to AM(<=50.00) space (run < 0) >= 5.000 um.
6309 0 GRAM2c: AM(>50.00) to AM(>50.00) space (run < 0) >= 5.000 um.
6313 0 GRAM2c: AM(>50.00) notch >= 5.000 um.
6338 0 GRAM2ba: AM(width >10um and <25um) to AM(width >10um and <25um) >= 3.00um !
6347 0 GRAM2ba: AM(width >10um and <25um) to AM(width <10um) >= 3.00um !
6355 0 GRAM2ba: AM(width >10um and <25um) to AM(width >25um) >= 3.00um !
6380 0 GRAM2b2: (AM space over IND_FILT) for AM(width > 25um and <= 50um) >= 4.00um !
6385 0 GRAM2b: AM(not under IND_FILT) width >10um  notch found !
6390 0 GRAM2ba: AM(under IND_FILT) width >10um and <25um) notch found !
6395 0 GRAM2b2: (AM over IND_FILT) width >25um and <=50um notch found !
6397 0 GRAM3: FT not within AM found!
6399 0 GRAM3: FTBAR not within AM found!
6401 0 GRAM3: FT must be within AM >= 1.000 um.
6403 0 GRAM3: FTBAR must be within AM >= 1.000 um.
6406 0 GRAM4: DV(within CHIPEDGE) not within AM found!
6409 0 GRAM4: LV(within CHIPEDGE) not within AM found!
6410 0 GRMA1: MA width >= 4.000 um.
6412 0 GRMA2: MA space >= 5.000 um.
6414 0 GRMA2: MA notch >= 5.000 um.
6417 0 GRMA4: DV(within CHIPEDGE) not within MA found!
6420 0 GRMA4: LV(within CHIPEDGE) not within MA found!
6422 0 GRML1: ML width >= 2.400 um.
6424 0 GRML2: ML space >= 2.400 um.
6426 0 GRML2: ML notch >= 2.400 um.
6428 0 GRML3: FT not within ML found!
6430 0 GRML3: FTBAR not within ML found!
6432 0 GRML3: FT must be within ML >= 0.600 um.
6434 0 GRML3: FTBAR must be within ML >= 0.600 um.
6437 0 GRML4: DV(within CHIPEDGE) not within ML found!
6440 0 GRML4: LV(within CHIPEDGE) not within ML found!
6449 0 GRQCAP1d: QT width (max) <= 1,000.0 um.
6458 0 GRQCAP1d: HT width (max) <= 1,000.0 um.
6459 0 GRQCAP1: QT width >= 8.000 um.
6460 0 GRQCAP1: HT width >= 8.000 um.
6461 0 GRQCAP1b: QT area (max per shape) <= 100,000.0 sq.um.
6462 0 GRQCAP1b: HT area (max per shape) <= 100,000.0 sq.um.
6464 0 GRQCAP2a: Non-rectangular QT shapes found!
6466 0 GRQCAP2a: Non-rectangular HT shapes found!
6469 0 GRQCAP2b: QT MIM aspect ratio > 3.0 found!
6472 0 GRQCAP2b: HT MIM aspect ratio > 3.0 found!
6474 0 GRQCAP2: QT space >= 5.000 um.
6476 0 GRQCAP2: HT space >= 5.000 um.
6477 0 GRQCAP3: QT not within MT found!
6478 0 GRQCAP3a: HT not within QT found!
6480 0 GRQCAP3: QT must be within MT >= 2.000 um.
6482 0 GRQCAP3a: HT must be within QT >= 2.000 um.
6486 0 GRQCAP4: QT(touching HT) not touching FT(outside of HT) found!
6487 0 GRQCAP4: FT straddling QT found!
6488 0 GRQCAP4b: FT straddling HT found!
6493 0 GRQCAP4a: (MT touching QT) touching V1 found!
6498 0 GRQCAP4a: (MT touching QT) touching V2 found!
6503 0 GRQCAP4a: (MT touching QT) touching V3 found!
6508 0 GRQCAP4a: (MT touching QT) touching V4 found!
6513 0 GRQCAP4a: (MT touching QT) touching V5 found!
6515 0 GRQCAP4: FT within QT >= 2.000 um.
6517 0 GRQCAP4b: FT within HT >= 2.000 um.
6518 0 GRQCAP4c: FT to HT space >= 2.000 um.
6519 0 GRQCAP5: FT to adjacent QT >= 2.000 um.
6520 0 GRQCAP5: FTBAR to adjacent QT >= 2.000 um.
6521 0 GRQCAP6: FTBAR touching QT found!
6525 0 GRQCAP8b: QT straddling BB(not touching (PC or DI)) found!
6526 0 GRQCAP8b: QT straddling NW(not touching (PC or DI)) found!
6528 0 GRQCAP8b: QT within BB(not touching (PC or DI)) >= 4.000 um.
6530 0 GRQCAP8b: QT within NW(not touching (PC or DI)) >= 4.000 um.
6533 0 GRQCAP12b: QT(covered by NW) within NW >= 4.000 um.
6537 0 GRQCAP16: NS to adjacent QT >= 4.600 um.
6538 0 GRQCAP16b: NW to adjacent QT(not touching {NW,PC,RX}) >= 4.600 um.
6547 0 GRQCAP17: (QT expanded by 2.0) to RX space >= 2.800 um.
6548 0 GRIND11: Invalid layer under IND_FLT found! (BN)
6549 0 GRIND11: Invalid layer under IND_FLT found! (BP)
6550 0 GRIND11: Invalid layer under IND_FLT found! (CABAR)
6551 0 GRIND11: Invalid layer under IND_FLT found! (LV)
6553 0 GRIND11: Invalid layer under IND_FLT found! (LVDUMMY)
6554 0 GRIND11: M1 straddling IND_FLT found!
6557 0 GRIND11: Invalid layer under IND_FLT found! (M2)
6560 0 GRIND11: Invalid layer under IND_FLT found! (M3)
6563 0 GRIND11: Invalid layer under IND_FLT found! (M4)
6566 0 GRIND11: Invalid layer under IND_FLT found! (M5)
6568 0 GRIND11: Invalid layer under IND_FLT found! (MT)
6569 0 GRIND11: Invalid layer under IND_FLT found! (NS)
6570 0 GRIND11: Invalid layer under IND_FLT found! (NW)
6571 0 GRIND11: Invalid layer under IND_FLT found! (OP)
6572 0 GRIND11: Invalid layer under IND_FLT found! (QT)
6573 0 GRIND11: Invalid layer under IND_FLT found! (RN)
6576 0 GRIND11: Invalid layer under IND_FLT found! (RX)
6577 0 GRIND11: RX straddling IND_FLT found!
6578 0 GRIND12: NS to IND_FILT space >= 4.600 um.
6583 0 GRIND13: AM(over IND_FLT) not covered by BB found!
6584 0 GRIND13: E1(over IND_FLT) not covered by BB found!
6585 0 GRIND13: MA(over IND_FLT) not covered by BB found!
6586 0 GRIND13: ML(over IND_FLT) not covered by BB found!
6587 0 GRIND16: (BB touch IND_FLT) touching BP found!
6589 0 GRIND16: (BB touch IND_FLT) touching (PC not touching IND_FLT) found!
6591 0 GRIND16: (BB touch IND_FLT) touching (RX not touching IND_FLT) found!
6607 0 ERROR: SHORTED INDUCTOR COILS FOUND!
6622 0 GRTL1b: (AM over TLINE) width (max) <= 25.00 um.
6631 0 GRTL1b: (MA over TLINE) width (max) <= 25.00 um.
6640 0 GRTL1b: (ML over TLINE) width (max) <= 25.00 um.
6642 0 GRTL2a: TLINE overlap past AM >= 20.00 um.
6644 0 GRTL2a: TLINE overlap past MA >= 20.00 um.
6646 0 GRTL2a: TLINE overlap past ML >= 20.00 um.
6648 0 GRTL2b: AM overlap past TLINE >= 1.00 um
6650 0 GRTL2b: MA overlap past TLINE >= 1.00 um
6652 0 GRTL2b: ML overlap past TLINE >= 1.00 um
6661 0 GRTL3b: (AM over TLINE) length (min) >= 100.00 um.
6664 0 GRTL3b: (MA over TLINE) length (min) >= 100.00 um.
6667 0 GRTL3b: (ML over TLINE) length (min) >= 100.00 um.
6668 0 GRTL3a: (AM over TLINE) area (min) >= 400.00 sq.um.
6669 0 GRTL3a: (MA over TLINE) area (min) >= 400.00 sq.um.
6670 0 GRTL3a: (ML over TLINE) area (min) >= 400.00 sq.um.
6674 0 GRTL4b: (AM over TLINE) length (max) >= 1500.00 um.
6678 0 GRTL4b: (MA over TLINE) length (max) >= 1500.00 um.
6682 0 GRTL4b: (ML over TLINE) length (max) >= 1500.00 um.
6683 0 GRTL4a: (AM over TLINE) area (max) >= 37,500.00 sq.um.
6684 0 GRTL4a: (MA over TLINE) area (max) >= 37,500.00 sq.um.
6685 0 GRTL4a: (ML over TLINE) area (max) >= 37,500.00 sq.um.
6686 0 GRTL5: (AM over TLINE) not within BB found!
6687 0 GRTL5: (MA over TLINE) not within BB found!
6688 0 GRTL5: (ML over TLINE) not within BB found!
6690 0 GRTL5: (AM over TLINE) must be within BB >= 4.00 um.
6692 0 GRTL5: (MA over TLINE) must be within BB >= 4.00 um.
6694 0 GRTL5: (ML over TLINE) must be within BB >= 4.00 um.
6695 0 GRTL6a: Invalid layer under TLINE found! (M1)
6696 0 GRTL6a: Invalid layer under TLINE found! (M2)
6697 0 GRTL6a: Invalid layer under TLINE found! (M3)
6698 0 GRTL6a: Invalid layer under TLINE found! (M4)
6699 0 GRTL6a: Invalid layer under TLINE found! (M5)
6700 0 GRTL6a: Invalid layer under TLINE found! (MT)
6701 0 GRTL6a: Invalid layer under TLINE found! (NS)
6702 0 GRTL6a: Invalid layer under TLINE found! (NW)
6703 0 GRTL6a: Invalid layer under TLINE found! (PC)
6704 0 GRTL6a: Invalid layer under TLINE found! (RX)
6706 0 GRTL6b: (AM over TLINE) space >= 40.00 um.
6708 0 GRTL6b: (MA over TLINE) space >= 40.00 um.
6710 0 GRTL6b: (ML over TLINE) space >= 40.00 um.
6712 0 GRTL9: Non-rectangular (AM over TLINE) found!
6714 0 GRTL9: Non-rectangular (MA over TLINE) found!
6716 0 GRTL9: Non-rectangular (ML over TLINE) found!
6725 0 GR780: PCING width == 0.160 um.(error > )
6726 0 GR780 PCING: width == 0.160 um.(error < )
6728 0 GR782: PCING to PCING space >= 0.420 um.
6729 0 GR782: PCING to PC    space >= 0.420 um.
6730 0 GR782: PCING to RX    space >= 0.420 um.
6731 0 GR782: PCING to CA    space >= 0.420 um.
6732 0 GR782: PCING to CABAR space >= 0.420 um.
6735 0 GR782: PCING touching (PC, RX, or CA/CABAR) shapes found
6736 0 GR783: PCING arm length (from corner to end) >= 2.000 um.
6745 0 GREF01: PCFUSE width == 0.18 um.(error >)
6746 0 GREF01: PCFUSE width == 0.18 um.(error <)
6747 0 GREF02: PCFUSE length == 1.20 um.(error <)
6748 0 GREF02: PCFUSE length == 1.20 um.(error >)
6751 0 GREF03: Non-rectangular PCFUSE found!
6753 0 GREF03a: Non-rectangular (PC touching PCFUSE) found!
6754 0 GREF03: 45 degree PCFUSE found
6755 0 GREF03a: 45 degree (PC touching PCFUSE) found
6757 0 GREF04: PCFUSE space >= 2.50 um.
6758 0 GREF05: PCFUSE over BB found!
6759 0 GREF05: PCFUSE over BFMOAT found!
6760 0 GREF05: PCFUSE over CA found!
6761 0 GREF05: PCFUSE over DG found!
6762 0 GREF05: PCFUSE over K1 found!
6763 0 GREF05: PCFUSE over M1 found!
6764 0 GREF05: PCFUSE over M2 found!
6766 0 GREF05: PCFUSE over MT found!
6767 0 GREF05: PCFUSE over NS found!
6768 0 GREF05: PCFUSE over NW found!
6769 0 GREF05: PCFUSE over OP found!
6770 0 GREF05: PCFUSE over PC found!
6771 0 GREF05: PCFUSE over QT found!
6772 0 GREF05: PCFUSE over RP found!
6773 0 GREF05: PCFUSE over RR found!
6774 0 GREF05: PCFUSE over RX found!
6776 0 GREF06: PCFUSE to BB space >= 2.50 um.
6777 0 GREF06: PCFUSE to BFMOAT space >= 2.50 um.
6778 0 GREF06: PCFUSE to DG space >= 2.50 um.
6779 0 GREF06: PCFUSE to K1 space >= 2.50 um.
6780 0 GREF06: PCFUSE to M2 space >= 2.50 um.
6781 0 GREF06: PCFUSE to MT space >= 2.50 um.
6782 0 GREF06: PCFUSE to NS space >= 2.50 um.
6783 0 GREF06: PCFUSE to NW space >= 2.50 um.
6784 0 GREF06: PCFUSE to OP space >= 2.50 um.
6785 0 GREF06: PCFUSE to QT space >= 2.50 um.
6786 0 GREF06: PCFUSE to RP space >= 2.50 um.
6787 0 GREF06: PCFUSE to RR space >= 2.50 um.
6788 0 GREF06: PCFUSE to RX space >= 2.50 um.
6789 0 GREF06: PCFUSE to V1 space >= 2.50 um.
6790 0 GREF07a: PCFUSE not within BP found!
6791 0 GREF07b: (PC touching PCFUSE) not within BP found!
6793 0 GREF07a: PCFUSE must be within BP >= 0.30 um.
6795 0 GREF07b: (PC touching PCFUSE) must be within BP >= 0.30 um.
6802 0 GREF08a: PCFUSE abutting more than 1 anode found!
6803 0 GREF08a: PCFUSE abutting more than 1 cathode found!
6805 0 GREF08: PCFUSE (small end) not abutting a PC shape found!
6807 0 GREF08b: PCFUSE to (PC not touching PCFUSE) space >= 2.50 um.
6809 0 GREF09: PCFUSE to (M1 not touching (PC touch PCFUSE)) space >= 2.50 um.
6810 0 GREF10: (PC touching PCFUSE) not touching any CA's found!
6811 0 GREF10: (PC touching PCFUSE) touching less than 4 CA's found!
6812 0 GREF10: (PC touching PCFUSE) touching more than 4 CA's found!
6821 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error >)
6822 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error <)
6823 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error <)
6824 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error >)
6833 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error >)
6834 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error <)
6835 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error >)
6836 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error <)
6844 0 GREF13: (M1 touching (PC touching PCFUSE)) (anode) width <= 1.20 um.
6846 0 GREF14: (M1 touching (PC touching PCFUSE)) (cathode) width <= 2.50 um.
6847 0 GREF15: PCFUSE to (M1 touching (PC touching PCFUSE)) space >= 1.00 um.
6867 0 GREF16: PCFUSE not centered on PC anode found!
6869 0 GREF16: PCFUSE not centered on PC cathode found!
6870 0 GREF18: (BP touching PCFUSE) width >= 0.720 um.
6872 0 GREF19: (BP touching PCFUSE) touching BB found!
6873 0 GREF19: (BP touching PCFUSE) touching DG found!
6874 0 GREF19: (BP touching PCFUSE) touching MOSVAR found!
6875 0 GREF19: (BP touching PCFUSE) touching NW found!
6876 0 GREF19: (BP touching PCFUSE) touching (PC over OP)... found!
6877 0 GREF19: (BP touching PCFUSE) touching (ZEROVT + 0.72) found!
6878 0 GREF19: (BP touching PCFUSE) to BB space >= 0.44 um.
6879 0 GREF19: (BP touching PCFUSE) to DG space >= 0.44 um.
6880 0 GREF19: (BP touching PCFUSE) to MOSVAR space >= 0.44 um.
6881 0 GREF19: (BP touching PCFUSE) to NW space >= 0.44 um.
6882 0 GREF19: (BP touching PCFUSE) to (PC over OP)... space >= 0.44 um.
6883 0 GREF19: (BP touching PCFUSE) to (ZEROVT + 0.72) space >= 0.44 um.
6885 0 GREF20: (BP touching PCFUSE) touching (BP touching OP) found!
6888 0 GREF20: (BP touch PCFUSE) touch (BP touch (PC no touch PCFUSE)) found!
6890 0 GREF20: (BP touching PCFUSE) touching (BP touching RX) found!
6892 0 GR941b: DV PAD space >= 11.00 um.
6900 0 GR942b: DV(pad) to any other shape (AM) >= 3.00 um.
6901 0 GR942b: DV(pad) to any other shape (DG) >= 3.00 um.
6902 0 GR942b: DV(pad) to any other shape (NR) >= 3.00 um.
6903 0 GR942b: DV(pad) to any other shape (PR) >= 3.00 um.
6904 0 GR942b: DV(pad) to any other shape (E1) >= 3.00 um.
6905 0 GR942b: DV(pad) to any other shape (JD) >= 3.00 um.
6906 0 GR942b: DV(pad) to any other shape (K1) >= 3.00 um.
6907 0 GR942b: DV(pad) to any other shape (MA) >= 3.00 um.
6908 0 GR942b: DV(pad) to any other shape (ML) >= 3.00 um.
6909 0 GR942b: DV(pad) to any other shape (MT) >= 3.00 um.
6910 0 GR942b: DV(pad) to any other shape (OP) >= 3.00 um.
6911 0 GR942b: DV(pad) to any other shape (GATE) >= 3.00 um.
6912 0 GR942b: DV(pad) to any other shape (PCFUSE) >= 3.00 um.
6913 0 GR942b: DV(pad) to any other shape (QT) >= 3.00 um.
6914 0 GR942b: DV(pad) to any other shape (RR) >= 3.00 um.
6915 0 GR942b: DV(pad) to any other shape (RP) >= 3.00 um.
6919 0 GR945b: DV must be within CHIPEDGE (Max) <= 190.00 um.
6921 0 GR946b: Non-rectangular DV pad found!
6922 0 GR946b: DV pad width (must be rectanglular) >= 62.00 um.
6932 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
6943 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
6945 0 GR946g: DV pad width >= 62.0 um and length >= 95.0 um !
6952 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
6954 0 GR948b1: DV must be within AM >= 3.00 um.
6956 0 GR948b1: DV must be within MA >= 3.00 um.
6958 0 GR948b1: DV must be within ML >= 3.00 um.
6959 0 GR951: no shapes allowed below a pad via (DG)
6960 0 GR951: no shapes allowed below a pad via (E1)
6961 0 GR951: no shapes allowed below a pad via (GATE)
6962 0 GR951: no shapes allowed below a pad via (JD)
6963 0 GR951: no shapes allowed below a pad via (K1)
6964 0 GR951: no shapes allowed below a pad via (MT)
6965 0 GR951: no shapes allowed below a pad via (NR)
6966 0 GR951: no shapes allowed below a pad via (OP)
6967 0 GR951: no shapes allowed below a pad via (PCFUSE)
6968 0 GR951: no shapes allowed below a pad via (PR)
6969 0 GR951: no shapes allowed below a pad via (QT)
6970 0 GR951: no shapes allowed below a pad via (RP)
6971 0 GR951: no shapes allowed below a pad via (RR)
7046 0 GR956: M1 width (under (pad +3.00)) <= 8.400 um.
7055 0 GR956: M2 width (under (pad +3.00)) <= 8.400 um.
7064 0 GR956: M3 width (under (pad +3.00)) <= 8.400 um.
7073 0 GR956: M4 width (under (pad +3.00)) <= 8.400 um.
7082 0 GR956: M5 width (under (pad +3.00)) <= 8.400 um.
7091 0 GR956: MT width (under (pad +3.00)) <= 8.400 um.
7094 0 GR956a: M1 enclosed area (under (pad +3.00)) found!
7097 0 GR956a: M2 enclosed area (under (pad +3.00)) found!
7100 0 GR956a: M3 enclosed area (under (pad +3.00)) found!
7103 0 GR956a: M4 enclosed area (under (pad +3.00)) found!
7106 0 GR956a: M5 enclosed area (under (pad +3.00)) found!
7109 0 GR956a: MT enclosed area (under (pad +3.00)) found!
7111 0 GR957: M1(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7113 0 GR957: M1(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7115 0 GR957: M2(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7117 0 GR957: M2(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7119 0 GR957: M3(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7121 0 GR957: M3(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7123 0 GR957: M4(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7125 0 GR957: M4(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7127 0 GR957: M5(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7129 0 GR957: M5(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7131 0 GR957: MT(>= 5.88um) space (under (pad +3.00)) >= 1.600 um.
7133 0 GR957: MT(>= 5.88um) notch (under (pad +3.00)) >= 1.600 um.
7137 0 GRBONDPAD1: BONDPAD overlap past LASTMETAL >= 0.100 um.
7140 0 GRBONDPAD3: LASTMETAL(over BONDPAD) not within (BB or PC) found!
7142 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within BB >= 4.900 um.
7144 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within PC >= 4.900 um.
7145 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching BP found!
7146 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching E1 found!
7147 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching K1 found!
7148 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M1 found!
7149 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M2 found!
7150 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M3 found!
7151 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M4 found!
7152 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M5 found!
7153 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching MT found!
7154 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching NW found!
7155 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching RX found!
7156 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to BP space >= 4.900 um.
7157 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to E1 space >= 4.900 um.
7158 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to K1 space >= 4.900 um.
7159 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M1 space >= 4.900 um.
7160 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M2 space >= 4.900 um.
7161 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M3 space >= 4.900 um.
7162 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M4 space >= 4.900 um.
7163 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M5 space >= 4.900 um.
7164 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to MT space >= 4.900 um.
7165 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to NW space >= 4.900 um.
7166 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to PC space >= 4.900 um.
7167 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to RX space >= 4.900 um.
7172 0 WARNING: YOU HAVE BOTH C4 AND WIREBOND PADS IN THIS DESIGN
7197 0 GRF20: M2FILL area <= 144.00 sq. um.
7198 0 GRF20: M3FILL area <= 144.00 sq. um.
7199 0 GRF20: M4FILL area <= 144.00 sq. um.
7200 0 GRF20: M5FILL area <= 144.00 sq. um.
7201 0 GRF20: MTFILL area <= 144.00 sq. um.
7203 0 # INFO: CMRF-7sf ASSURA DRC DECK (REV DATE 25/01/2005) #
