0 0 dataAuditErrors
361 0 SBLK without OP
462 0 efuse device without bp
485 0 efuse device touching ns,rx,jd,pi,rn,nw,nr,pr,bb,dg,tg,rr,rp,pd,op
488 0 HAVAR device missing bb
505 0 HAVAR device touching pi,nw,nr,pr,dg,tg,pc,rr,rp,pd,op
544 0 SBD device without NS
545 0 NS straddling SBD device
556 0 SBD device touching jd,pi,nw,nr,pr,dg,tg,pc,rr,rp,op
580 0 SBDNW device must be covered by NW
592 0 SBDNW device touching ns,jd,pi,rn,nr,pr,dg,tg,pc,rr,rp,op
626 0 PSBD device touching ns,jd,rn,nr,pr,dg,tg,pc,rr,rp,op
627 0 PSBD device missing bb
658 0 DI Diode device without bp
672 0 DI Diode device touching ns,jd,pi,rn,nr,pr,bb,dg,tg,pc,rr,rp,pd,op
709 0 DIPI Diode device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
711 0 DIPI Diode device touching nw,bp
769 0 pcap device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
770 0 pcap device touching tg
775 0 N+ diffusion in pcap pwell found
814 0 vlnpn device touching ns,jd,rn,nr,pr,bb,dg,rr,rp,pd,op
853 0 mosvar device touching dg
895 0 P+ diffusion in ncap nwell found
916 0 mosvar or ncap device touching ns,jd,pi,rn,nr,pr,bp,rr,rp,pd,op
937 0 JFET device not over pi
967 0 JFET device touching ns,jd,rn,nr,pr,bb,dg,tg,pc,rr,rp,pd,op
1295 0 Dual gate poly device without M1/CA connection
1317 0 N+ Diffused Resistor device touching ns,nw,nr,pr
1501 0 FET device touching ns,jd,rn,bb,rr,rp,pd,op
1521 0 Diffused Resistor device touching bb,dg,pc
1530 0 Diffused Resistor device touching ns,jd,rn,pd,rr,rp,nr,pr
1612 0 Polysilicon Resistor device touching ns,jd,rx,rn,tg
1618 0 Polysilicon Resistor device not covered by P+ implant
1623 0 Polysilicon Resistor device BB touching pi,nw,nr,pr
1627 0 Polysilicon Resistor device RR or RP touching nr,pr
1749 0 (AM res) not covered by mask AM
1751 0 (MT res) not covered by mask MT
1753 0 (M5 res) not covered by mask M5
1755 0 (M4 res) not covered by mask M4
1757 0 (M3 res) not covered by mask M3
1759 0 (M2 res) not covered by mask M2
1761 0 (M1 res) not covered by mask M1
1852 0 Overlapping transmission lines - terminals must abut filters
1910 0 inductor device touching ns,jd,pi,rn,nw,nr,pr,dg,tg,pc,rr,rp,pd,op
1997 0 M3 and M4 inside enhanced Inductor model must have the same dimension as MT
2001 0 M3/M4 inside standard inductor model is not allowed
2009 0 M4 and M5 inside enhanced Inductor model must have the same dimension as MT
2013 0 M4/M5 inside standard inductor model is not allowed
2113 0 Missing v3 vias on symind coils between m3 and m4
2116 0 Missing v4 vias on symind coils between m4 and m5
2119 0 Missing v5 vias on symind coils between m5 and mt
2122 0 Missing v3 vias on symind coils between m3 and m4
2125 0 Missing v4 vias on symind coils between m4 and m5
2128 0 Missing v5 vias on symind coils between m5 and mt
2131 0 Missing ft vias on symind coils between mt and am
2134 0 Missing ft vias on symind coils between mt and am
2137 0 Missing ft vias on ind coils between mt and am
2179 0 AM signal wire exiting symetrical inductor straddling metal coil outside the pin
2183 0 Center tap signal wire exiting symetrical inductor outside CT pin
2364 0 AM signal wire not exiting transmission line at port, shorted, or open
2385 0 M4 signal wire not exiting transmission line at port, shorted, or open
2400 0 M5 signal wire not exiting transmission line at port, shorted, or open
2424 0 MT signal wire not exiting transmission line at port, shorted, or open
2448 0 M3 signal wire not exiting transmission line at port, shorted, or open
2469 0 M2 signal wire not exiting transmission line at port, shorted, or open
2620 0 No FT via over HT
2621 0 No FT via over QT
2642 0 MODEL concern - K1 resistor not totally over STI substrate
3083 0 nw_StampErrorConnect
3087 0 nw_StampErrorFloat
3088 0 nw_StampErrorMult
3091 0 nw_StampErrorConnect
3095 0 nw_StampErrorFloat
3096 0 nw_StampErrorMult
3099 0 ncap_nw_StampErrorConnect
3103 0 ncap_nw_StampErrorFloat
3104 0 ncap_nw_StampErrorMult
3107 0 well_StampErrorConnect
3111 0 well_StampErrorFloat
3112 0 well_StampErrorMult
3115 0 pi_StampErrorConnect
3119 0 pi_StampErrorFloat
3120 0 pi_StampErrorMult
3123 0 pwell_StampErrorConnect
3127 0 pwell_StampErrorFloat
3128 0 pwell_StampErrorMult
3131 0 ns_StampErrorConnect
3135 0 ns_StampErrorFloat
3136 0 ns_StampErrorMult
3138 0 substrate_ptap_StampErrorCon
3143 0 substrate_StampErrorCon
3150 0 sub_sti_StampErrorCon
3155 0 sub1K_StampErrorConnect
3161 0 sub50_StampErrorConnect
3169 0 Mixed voltage net found : 3V3 or 5V diffusion is connected to 1.8V gate
3171 0 ptap connected to POWER net found !
3173 0 pwtap connected to POWER net found !
3178 0 forward biased ptie device found ! [tdpdnw/diodepnw] 
3183 0 forward biased ntie device found ! [tdndsx,tdndpw/diodenx,diodendpw] 
3185 0 NW ring not connected to a power net found !
10279 0 vlnpn collector not connected to nw_ring
13602 0 ###### SEVEN levels of metal M1-M2-M3-M4-M5-MT-AM #####
15789 0 malformed device nfeti_dev
15790 0 malformed device nfeti_dev_psp
15791 0 malformed device nfeti_dev_b
15792 0 malformed device nfeti_dev_psp_b
15793 0 malformed device nfet6_dev
15794 0 malformed device nfet6_dev_psp
15795 0 malformed device nfet6_dev_b
15796 0 malformed device nfet6_dev_psp_b
15797 0 malformed device nfeti_dev_MV
15798 0 malformed device nfeti_dev_psp_MV
15799 0 malformed device nfet6_dev_MV
15800 0 malformed device nfet6_dev_psp_MV
15801 0 malformed device nfeti_dev_HV
15802 0 malformed device nfeti_dev_psp_HV
15803 0 malformed device nfet6_dev_HV
15804 0 malformed device nfet6_dev_psp_HV
15805 0 malformed device nfeti_dev_TG
15806 0 malformed device nfet6_dev_TG
15807 0 malformed device nfet_dpw
15808 0 malformed device nfet_dev
15809 0 malformed device nfet_dpw_psp
15810 0 malformed device nfet_dev_psp
15811 0 malformed device nfzv_dev
15812 0 malformed device nfzv_dev_HV
15813 0 malformed device nfet_dpw_MV
15814 0 malformed device nfet_dev_MV
15815 0 malformed device nfet_dpw_psp_MV
15816 0 malformed device nfet_dev_psp_MV
15817 0 malformed device nfet_dpw_HV
15818 0 malformed device nfet_dev_HV
15819 0 malformed device nfet_dpw_psp_HV
15820 0 malformed device nfet_dev_psp_HV
15821 0 malformed device nfet_dpw_TG
15822 0 malformed device nfet_dev_TG
15823 0 malformed device nfet_dev_HVT
15824 0 malformed device nfet_dev_HVT_b
15825 0 malformed device nfet_dpw_b
15826 0 malformed device nfet_dev_b
15827 0 malformed device nfet_dpw_psp_b
15828 0 malformed device nfet_dev_psp_b
15829 0 malformed device pfet_dev
15830 0 malformed device pfet_dev_psp
15831 0 malformed device pfet_dev_MV
15832 0 malformed device pfet_dev_psp_MV
15833 0 malformed device pfet_dev_HV
15834 0 malformed device pfet_dev_psp_HV
15835 0 malformed device pfet_dev_TG
15836 0 malformed device pfet_dev_SCG
15837 0 malformed device pfet_dev_HVT
15838 0 malformed device pfet_dev_HVT_b
15839 0 malformed device pfet_dev_b
15840 0 malformed device pfet_dev_psp_b
15841 0 malformed device nfeti_mul
15842 0 malformed device nfeti_mul_psp
15843 0 malformed device nfet6_mul
15844 0 malformed device nfet6_mul_psp
15845 0 malformed device nfeti_mul_MV
15846 0 malformed device nfeti_mul_psp_MV
15847 0 malformed device nfet6_mul_MV
15848 0 malformed device nfet6_mul_psp_MV
15849 0 malformed device nfeti_mul_HV
15850 0 malformed device nfeti_mul_psp_HV
15851 0 malformed device nfet6_mul_HV
15852 0 malformed device nfet6_mul_psp_HV
15853 0 malformed device nfeti_mul_TG
15854 0 malformed device nfet6_mul_TG
15856 0 malformed device nfet_mul
15858 0 malformed device nfet_mul_psp
15859 0 malformed device nfzv_mul
15860 0 malformed device nfzv_mul_HV
15862 0 malformed device nfet_mul_MV
15864 0 malformed device nfet_mul_psp_MV
15866 0 malformed device nfet_mul_HV
15868 0 malformed device nfet_mul_psp_HV
15870 0 malformed device nfet_mul_TG
15871 0 malformed device nfet_mul_HVT
15872 0 malformed device pfet_mul
15873 0 malformed device pfet_mul_psp
15874 0 malformed device pfet_mul_MV
15875 0 malformed device pfet_mul_psp_MV
15876 0 malformed device pfet_mul_HV
15877 0 malformed device pfet_mul_psp_HV
15878 0 malformed device pfet_mul_TG
15879 0 malformed device pfet_mul_SCG
15880 0 malformed device pfet_mul_HVT
15881 0 malformed device nfRFi_dev
15882 0 malformed device nfRFi_dev_psp
15883 0 malformed device nfRF6_dev
15884 0 malformed device nfRF6_dev_psp
15885 0 malformed device nfRFi_dev_MV
15886 0 malformed device nfRFi_dev_psp_MV
15887 0 malformed device nfRF6_dev_MV
15888 0 malformed device nfRF6_dev_psp_MV
15889 0 malformed device nfRFi_dev_HV
15890 0 malformed device nfRFi_dev_psp_HV
15891 0 malformed device nfRF6_dev_HV
15892 0 malformed device nfRF6_dev_psp_HV
15893 0 malformed device nfRFi_dev_TG
15894 0 malformed device nfRF6_dev_TG
15896 0 malformed device nfRF_dev
15898 0 malformed device nfRF_dev_psp
15900 0 malformed device nfRF_dev_MV
15902 0 malformed device nfRF_dev_psp_MV
15904 0 malformed device nfRF_dev_HV
15906 0 malformed device nfRF_dev_psp_HV
15908 0 malformed device nfRF_dev_TG
15909 0 malformed device pfRF_dev
15910 0 malformed device pfRF_dev_psp
15911 0 malformed device pfRF_dev_MV
15912 0 malformed device pfRF_dev_psp_MV
15913 0 malformed device pfRF_dev_HV
15914 0 malformed device pfRF_dev_psp_HV
15915 0 malformed device pfRF_dev_TG
15916 0 malformed device pfRF_dev_SCG
15917 0 malformed device nfRFi_mul
15918 0 malformed device nfRFi_mul_psp
15919 0 malformed device nfRF6_mul
15920 0 malformed device nfRF6_mul_psp
15921 0 malformed device nfRFi_mul_MV
15922 0 malformed device nfRFi_mul_psp_MV
15923 0 malformed device nfRF6_mul_MV
15924 0 malformed device nfRF6_mul_psp_MV
15925 0 malformed device nfRFi_mul_HV
15926 0 malformed device nfRFi_mul_psp_HV
15927 0 malformed device nfRF6_mul_HV
15928 0 malformed device nfRF6_mul_psp_HV
15929 0 malformed device nfRFi_mul_TG
15930 0 malformed device nfRF6_mul_TG
15932 0 malformed device nfRF_mul
15934 0 malformed device nfRF_mul_psp
15936 0 malformed device nfRF_mul_MV
15938 0 malformed device nfRF_mul_psp_MV
15940 0 malformed device nfRF_mul_HV
15942 0 malformed device nfRF_mul_psp_HV
15944 0 malformed device nfRF_mul_TG
15945 0 malformed device pfRF_mul
15946 0 malformed device pfRF_mul_psp
15947 0 malformed device pfRF_mul_MV
15948 0 malformed device pfRF_mul_psp_MV
15949 0 malformed device pfRF_mul_HV
15950 0 malformed device pfRF_mul_psp_HV
15951 0 malformed device pfRF_mul_TG
15952 0 malformed device pfRF_mul_SCG
15953 0 malformed device hvr_dev
15954 0 malformed device diffhavar_dev
15955 0 malformed device SBD
15956 0 malformed device SBDNW
15957 0 malformed device PSBD
15958 0 malformed device DI_diode
15959 0 malformed device DIPI_diode
15960 0 malformed device DI_VPNP
15961 0 malformed device ncap_dev
15962 0 malformed device ncap33_dev
15963 0 malformed device ncap50_dev
15964 0 malformed device diffmosvar_dev
15965 0 malformed device mosvar_dev
15966 0 malformed device mosvar50_dev
15967 0 malformed device p5pcdcap50_dev
15968 0 malformed device vlnpn_dev
15969 0 malformed device jfet_dev
15970 0 malformed device res_serpentine
15971 0 malformed device resnw_serpentine
15972 0 malformed device rnw6pc_dev
15974 0 malformed device res6pc_dev
15975 0 malformed device rnw6rr_dev
15977 0 malformed device res6rr_dev
15978 0 malformed device rnw6rp_dev
15980 0 malformed device res6rp_dev
15982 0 malformed device res6n_dev
15983 0 malformed device res6p_dev
15985 0 malformed device res6n_sblk
15986 0 malformed device res6p_sblk
15987 0 malformed device k1_dev_bb
15989 0 malformed device k1_dev_sx
15991 0 malformed device esdnsh_dev
15992 0 malformed device esdpsh_dev
15993 0 malformed device sub_dev
15995 0 malformed device ntie_device
15996 0 malformed device ptie_device
15997 0 malformed device corrPoint_dev_M2
15998 0 malformed device corrPoint_dev_PD
15999 0 malformed device corrPoint_dev_ND
16000 0 malformed device corrPoint_dev_PC
16001 0 malformed device corrPoint_dev_M1
16002 0 malformed device ESD_pdnw_diode
16003 0 malformed device ESD_pdnw_diode_GR_sized
16004 0 malformed device ESD_pdnw_diode_GR
16005 0 malformed device ESD_ndsx
16006 0 malformed device ESD_ndsx_GR_sized
16007 0 malformed device ESD_ndsx_GR
16008 0 malformed device MIMpi
16009 0 malformed device MIMnw
16010 0 malformed device MIMsx
16011 0 malformed device MIMhdpi
16012 0 malformed device MIMhdnw
16013 0 malformed device MIMhdsx
16014 0 malformed device MIMHKpi
16015 0 malformed device MIMHKnw
16016 0 malformed device MIMHKpc
16017 0 malformed device MIMHKsx
16018 0 malformed device DUALMIMpi
16019 0 malformed device DUALMIMnw
16020 0 malformed device DUALMIMsx
16021 0 malformed device DUALMIMhdpi
16022 0 malformed device DUALMIMhdnw
16023 0 malformed device DUALMIMhdsx
16025 0 malformed device vncap_top1
16026 0 malformed device vncap_tnw1
16028 0 malformed device vncap_topt
16029 0 malformed device vncap_tnwt
16031 0 malformed device vncap_top2
16032 0 malformed device vncap_tnw2
16034 0 malformed device vncap_top3
16035 0 malformed device vncap_tnw3
16037 0 malformed device vncap_top4
16038 0 malformed device vncap_tnw4
16040 0 malformed device vncap_top5
16041 0 malformed device vncap_tnw5
16042 0 malformed device am_transmission
16043 0 malformed device ind2_mtam_m1
16044 0 malformed device ind2_mtam_bb
16046 0 malformed device symind3_amam_bb
16048 0 malformed device symind3_amam_m1
16049 0 malformed device symind2_amam_bb
16050 0 malformed device symind2_amam_m1
16051 0 malformed device padOverDev
16052 0 malformed device bondPad_PC
16053 0 malformed device bondPad_BB
16054 0 malformed device efuse
16060 0 malformed device coupledA
16066 0 malformed device singleEndA
16071 0 malformed device coupledT
16076 0 malformed device singleEndT
16080 0 malformed device coupled5
16084 0 malformed device singleEnd5
16087 0 malformed device coupled4
16090 0 malformed device singleEnd4
16092 0 malformed device coupled3
16094 0 malformed device singleEnd3
16095 0 malformed device coupled2
16096 0 malformed device singleEnd2
16097 0 malformed device pdiode_dev
16098 0 malformed device ndiode_dev
16099 0 malformed device ndiode_dev
16100 0 malformed device nwdiode_dev1
16101 0 malformed device nwdiode_dev
16102 0 malformed device pwell_dev
16103 0 malformed device piwell_dev
18078 0 unstable device for piwell_dev_Device_337
18079 0 unstable device for pwell_dev_Device_336
18080 0 unstable device for nwdiode_dev_Device_335
18081 0 unstable device for nwdiode_dev1_Device_334
18082 0 unstable device for ndiode_dev_Device_333
18083 0 unstable device for ndiode_dev_Device_332
18084 0 unstable device for pdiode_dev_Device_331
18085 0 unstable device for am_RES_min_Device_330
18086 0 unstable device for m5_RES_min_Device_329
18087 0 unstable device for m5_RES_min_Device_327
18088 0 unstable device for m4_RES_min_Device_326
18089 0 unstable device for m4_RES_min_Device_324
18090 0 unstable device for m3_RES_min_Device_323
18091 0 unstable device for m3_RES_min_Device_321
18092 0 unstable device for m2_RES_min_Device_320
18093 0 unstable device for m2_RES_min_Device_318
18094 0 unstable device for mt_RES_min_Device_317
18095 0 unstable device for mt_RES_min_Device_315
18096 0 unstable device for m1_RES_min_Device_314
18097 0 unstable device for m1_RES_min_Device_312
18098 0 unstable device for singleEnd2_shield1
18099 0 unstable device for coupled2_shield1
18100 0 unstable device for singleEnd3_shield2
18101 0 unstable device for singleEnd3_shield1
18102 0 unstable device for coupled3_shield2
18103 0 unstable device for coupled3_shield1
18104 0 unstable device for singleEnd4_shield3
18105 0 unstable device for singleEnd4_shield2
18106 0 unstable device for singleEnd4_shield1
18107 0 unstable device for coupled4_shield3
18108 0 unstable device for coupled4_shield2
18109 0 unstable device for coupled4_shield1
18110 0 unstable device for singleEnd5_shield4
18111 0 unstable device for singleEnd5_shield3
18112 0 unstable device for singleEnd5_shield2
18113 0 unstable device for singleEnd5_shield1
18114 0 unstable device for coupled5_shield4
18115 0 unstable device for coupled5_shield3
18116 0 unstable device for coupled5_shield2
18117 0 unstable device for coupled5_shield1
18118 0 unstable device for singleEndT_shield5
18119 0 unstable device for singleEndT_shield4
18120 0 unstable device for singleEndT_shield3
18121 0 unstable device for singleEndT_shield2
18122 0 unstable device for singleEndT_shield1
18123 0 unstable device for coupledT_shield5
18124 0 unstable device for coupledT_shield4
18125 0 unstable device for coupledT_shield3
18126 0 unstable device for coupledT_shield2
18127 0 unstable device for coupledT_shield1
18128 0 unstable device for singleEndA_shieldT
18129 0 unstable device for singleEndA_shield5
18130 0 unstable device for singleEndA_shield4
18131 0 unstable device for singleEndA_shield3
18132 0 unstable device for singleEndA_shield2
18133 0 unstable device for singleEndA_shield1
18134 0 unstable device for coupledA_shieldT
18135 0 unstable device for coupledA_shield5
18136 0 unstable device for coupledA_shield4
18137 0 unstable device for coupledA_shield3
18138 0 unstable device for coupledA_shield2
18139 0 unstable device for coupledA_shield1
18140 0 unstable device for efuse_Device_269
18141 0 unstable device for bondPad_BB_Device_268
18142 0 unstable device for bondPad_PC_Device_267
18143 0 unstable device for padOverDev_Device_266
18144 0 unstable device for symind2_amam_m1_Device_265
18145 0 unstable device for symind2_amam_bb_Device_264
18146 0 unstable device for symind3_amam_m1_Device_261
18147 0 unstable device for symind3_amam_m1_Device_263
18148 0 unstable device for symind3_amam_bb_Device_260
18149 0 unstable device for symind3_amam_bb_Device_262
18150 0 unstable device for ind2_mtam_bb_Device_259
18151 0 unstable device for ind2_mtam_m1_Device_258
18152 0 unstable device for am_transmission_Device_257
18153 0 unstable device for vncap_tnw5_Device_256
18154 0 unstable device for vncap_top5_pwell
18155 0 unstable device for vncap_top5_subs
18156 0 unstable device for vncap_tnw4_Device_253
18157 0 unstable device for vncap_top4_pwell
18158 0 unstable device for vncap_top4_subs
18159 0 unstable device for vncap_tnw3_Device_250
18160 0 unstable device for vncap_top3_pwell
18161 0 unstable device for vncap_top3_subs
18162 0 unstable device for vncap_tnw2_Device_247
18163 0 unstable device for vncap_top2_pwell
18164 0 unstable device for vncap_top2_subs
18165 0 unstable device for vncap_tnwt_Device_244
18166 0 unstable device for vncap_topt_pwell
18167 0 unstable device for vncap_topt_subs
18168 0 unstable device for vncap_tnw1_Device_241
18169 0 unstable device for vncap_top1_pwell
18170 0 unstable device for vncap_top1_subs
18171 0 unstable device for DUALMIMhdsx_Device_238
18172 0 unstable device for DUALMIMhdnw_Device_237
18173 0 unstable device for DUALMIMhdpi_Device_236
18174 0 unstable device for DUALMIMsx_Device_235
18175 0 unstable device for DUALMIMnw_Device_234
18176 0 unstable device for DUALMIMpi_Device_233
18177 0 unstable device for MIMHKsx_Device_232
18178 0 unstable device for MIMHKpc_Device_231
18179 0 unstable device for MIMHKnw_Device_230
18180 0 unstable device for MIMHKpi_Device_229
18181 0 unstable device for MIMhdsx_Device_228
18182 0 unstable device for MIMhdnw_Device_227
18183 0 unstable device for MIMhdpi_Device_226
18184 0 unstable device for MIMsx_Device_225
18185 0 unstable device for MIMnw_Device_224
18186 0 unstable device for MIMpi_Device_223
18187 0 unstable device for ESD_ndsx_pi_Device_222
18188 0 unstable device for ESD_pdnw_pi_Device_221
18189 0 unstable device for ESD_ndsx_GR_Device_220
18190 0 unstable device for ESD_ndsx_GR_sized_Device_219
18191 0 unstable device for ESD_ndsx_Device_218
18192 0 unstable device for ESD_pdnw_diode_GR_Device_217
18193 0 unstable device for ESD_pdnw_diode_GR_sized_Device_216
18194 0 unstable device for ESD_pdnw_diode_Device_215
18195 0 unstable device for corrPoint_dev_M1_Device_214
18196 0 unstable device for corrPoint_dev_PC_Device_213
18197 0 unstable device for corrPoint_dev_ND_Device_212
18198 0 unstable device for corrPoint_dev_PD_Device_211
18199 0 unstable device for corrPoint_dev_M2_Device_210
18200 0 unstable device for ptie_device_Device_209
18201 0 unstable device for ntie_device_Device_207
18202 0 unstable device for ntie_device_Device_208
18203 0 unstable device for sub_dev_Device_206
18204 0 unstable device for esdpsh_dev_Device_205
18205 0 unstable device for esdnsh_dev_Device_203
18206 0 unstable device for esdnsh_dev_Device_204
18207 0 unstable device for k1_dev_sx_pwell
18208 0 unstable device for k1_dev_sx_subs
18209 0 unstable device for k1_dev_bb_Device_200
18210 0 unstable device for res6p_sblk_Device_199
18211 0 unstable device for res6n_sblk_pwell
18212 0 unstable device for res6n_sblk_subs
18213 0 unstable device for res6p_dev_Device_196
18214 0 unstable device for res6n_dev_pwell
18215 0 unstable device for res6n_dev_subs
18216 0 unstable device for res6rp_dev_pwell
18217 0 unstable device for res6rp_dev_subs
18218 0 unstable device for rnw6rp_dev_Device_191
18219 0 unstable device for res6rr_dev_pwell
18220 0 unstable device for res6rr_dev_subs
18221 0 unstable device for rnw6rr_dev_Device_188
18222 0 unstable device for res6pc_dev_pwell
18223 0 unstable device for res6pc_dev_subs
18224 0 unstable device for rnw6pc_dev_Device_185
18225 0 unstable device for resnw_serpentine_Device_184
18226 0 unstable device for res_serpentine_Device_183
18227 0 unstable device for jfet_dev_Device_182
18228 0 unstable device for vlnpn_dev_Device_181
18229 0 unstable device for pcap_dev_Device_180
18230 0 unstable device for p5pcdcap50_dev_Device_179
18231 0 unstable device for mosvar50_dev_Device_178
18232 0 unstable device for mosvar_dev_Device_177
18233 0 unstable device for diffmosvar_dev_Device_176
18234 0 unstable device for ncap50_dev_Device_175
18235 0 unstable device for ncap33_dev_Device_174
18236 0 unstable device for ncap_dev_Device_173
18237 0 unstable device for DI_VPNP_Device_172
18238 0 unstable device for DIPI_diode_Device_171
18239 0 unstable device for DI_diode_Device_170
18240 0 unstable device for PSBD_Device_169
18241 0 unstable device for SBDNW_Device_168
18242 0 unstable device for SBD_Device_167
18243 0 unstable device for diffhavar_dev_Device_166
18244 0 unstable device for hvr_dev_Device_165
18245 0 unstable device for pfRF_mul_SCG_Device_164
18246 0 unstable device for pfRF_mul_TG_Device_163
18247 0 unstable device for pfRF_mul_psp_HV_Device_162
18248 0 unstable device for pfRF_mul_HV_Device_161
18249 0 unstable device for pfRF_mul_psp_MV_Device_160
18250 0 unstable device for pfRF_mul_MV_Device_159
18251 0 unstable device for pfRF_mul_psp_Device_158
18252 0 unstable device for pfRF_mul_Device_157
18253 0 unstable device for nfRF_mul_TG_Device_155
18254 0 unstable device for nfRF_mul_TG_Device_156
18255 0 unstable device for nfRF_mul_psp_HV_Device_153
18256 0 unstable device for nfRF_mul_psp_HV_Device_154
18257 0 unstable device for nfRF_mul_HV_Device_151
18258 0 unstable device for nfRF_mul_HV_Device_152
18259 0 unstable device for nfRF_mul_psp_MV_Device_149
18260 0 unstable device for nfRF_mul_psp_MV_Device_150
18261 0 unstable device for nfRF_mul_MV_Device_147
18262 0 unstable device for nfRF_mul_MV_Device_148
18263 0 unstable device for nfRF_mul_psp_Device_145
18264 0 unstable device for nfRF_mul_psp_Device_146
18265 0 unstable device for nfRF_mul_Device_143
18266 0 unstable device for nfRF_mul_Device_144
18267 0 unstable device for nfRF6_mul_TG_Device_142
18268 0 unstable device for nfRFi_mul_TG_Device_141
18269 0 unstable device for nfRF6_mul_psp_HV_Device_140
18270 0 unstable device for nfRF6_mul_HV_Device_139
18271 0 unstable device for nfRFi_mul_psp_HV_Device_138
18272 0 unstable device for nfRFi_mul_HV_Device_137
18273 0 unstable device for nfRF6_mul_psp_MV_Device_136
18274 0 unstable device for nfRF6_mul_MV_Device_135
18275 0 unstable device for nfRFi_mul_psp_MV_Device_134
18276 0 unstable device for nfRFi_mul_MV_Device_133
18277 0 unstable device for nfRF6_mul_psp_Device_132
18278 0 unstable device for nfRF6_mul_Device_131
18279 0 unstable device for nfRFi_mul_psp_Device_130
18280 0 unstable device for nfRFi_mul_Device_129
18281 0 unstable device for pfRF_dev_SCG_Device_128
18282 0 unstable device for pfRF_dev_TG_Device_127
18283 0 unstable device for pfRF_dev_psp_HV_Device_126
18284 0 unstable device for pfRF_dev_HV_Device_125
18285 0 unstable device for pfRF_dev_psp_MV_Device_124
18286 0 unstable device for pfRF_dev_MV_Device_123
18287 0 unstable device for pfRF_dev_psp_Device_122
18288 0 unstable device for pfRF_dev_Device_121
18289 0 unstable device for nfRF_dev_TG_Device_119
18290 0 unstable device for nfRF_dev_TG_Device_120
18291 0 unstable device for nfRF_dev_psp_HV_Device_117
18292 0 unstable device for nfRF_dev_psp_HV_Device_118
18293 0 unstable device for nfRF_dev_HV_Device_115
18294 0 unstable device for nfRF_dev_HV_Device_116
18295 0 unstable device for nfRF_dev_psp_MV_Device_113
18296 0 unstable device for nfRF_dev_psp_MV_Device_114
18297 0 unstable device for nfRF_dev_MV_Device_111
18298 0 unstable device for nfRF_dev_MV_Device_112
18299 0 unstable device for nfRF_dev_psp_Device_109
18300 0 unstable device for nfRF_dev_psp_Device_110
18301 0 unstable device for nfRF_dev_Device_107
18302 0 unstable device for nfRF_dev_Device_108
18303 0 unstable device for nfRF6_dev_TG_Device_106
18304 0 unstable device for nfRFi_dev_TG_Device_105
18305 0 unstable device for nfRF6_dev_psp_HV_Device_104
18306 0 unstable device for nfRF6_dev_HV_Device_103
18307 0 unstable device for nfRFi_dev_psp_HV_Device_102
18308 0 unstable device for nfRFi_dev_HV_Device_101
18309 0 unstable device for nfRF6_dev_psp_MV_Device_100
18310 0 unstable device for nfRF6_dev_MV_Device_99
18311 0 unstable device for nfRFi_dev_psp_MV_Device_98
18312 0 unstable device for nfRFi_dev_MV_Device_97
18313 0 unstable device for nfRF6_dev_psp_Device_96
18314 0 unstable device for nfRF6_dev_Device_95
18315 0 unstable device for nfRFi_dev_psp_Device_94
18316 0 unstable device for nfRFi_dev_Device_93
18317 0 unstable device for pfet_mul_HVT_Device_92
18318 0 unstable device for pfet_mul_SCG_Device_91
18319 0 unstable device for pfet_mul_TG_Device_90
18320 0 unstable device for pfet_mul_psp_HV_Device_89
18321 0 unstable device for pfet_mul_HV_Device_88
18322 0 unstable device for pfet_mul_psp_MV_Device_87
18323 0 unstable device for pfet_mul_MV_Device_86
18324 0 unstable device for pfet_mul_psp_Device_85
18325 0 unstable device for pfet_mul_Device_84
18326 0 unstable device for nfet_mul_HVT_Device_83
18327 0 unstable device for nfet_mul_TG_Device_81
18328 0 unstable device for nfet_mul_TG_Device_82
18329 0 unstable device for nfet_mul_psp_HV_Device_79
18330 0 unstable device for nfet_mul_psp_HV_Device_80
18331 0 unstable device for nfet_mul_HV_Device_77
18332 0 unstable device for nfet_mul_HV_Device_78
18333 0 unstable device for nfet_mul_psp_MV_Device_75
18334 0 unstable device for nfet_mul_psp_MV_Device_76
18335 0 unstable device for nfet_mul_MV_Device_73
18336 0 unstable device for nfet_mul_MV_Device_74
18337 0 unstable device for nfzv_mul_HV_Device_72
18338 0 unstable device for nfzv_mul_Device_71
18339 0 unstable device for nfet_mul_psp_Device_69
18340 0 unstable device for nfet_mul_psp_Device_70
18341 0 unstable device for nfet_mul_Device_67
18342 0 unstable device for nfet_mul_Device_68
18343 0 unstable device for nfet6_mul_TG_Device_66
18344 0 unstable device for nfeti_mul_TG_Device_65
18345 0 unstable device for nfet6_mul_psp_HV_Device_64
18346 0 unstable device for nfet6_mul_HV_Device_63
18347 0 unstable device for nfeti_mul_psp_HV_Device_62
18348 0 unstable device for nfeti_mul_HV_Device_61
18349 0 unstable device for nfet6_mul_psp_MV_Device_60
18350 0 unstable device for nfet6_mul_MV_Device_59
18351 0 unstable device for nfeti_mul_psp_MV_Device_58
18352 0 unstable device for nfeti_mul_MV_Device_57
18353 0 unstable device for nfet6_mul_psp_Device_56
18354 0 unstable device for nfet6_mul_Device_55
18355 0 unstable device for nfeti_mul_psp_Device_54
18356 0 unstable device for nfeti_mul_Device_53
18357 0 unstable device for pfet_dev_psp_b_Device_52
18358 0 unstable device for pfet_dev_b_Device_51
18359 0 unstable device for pfet_dev_HVT_b_Device_50
18360 0 unstable device for pfet_dev_HVT_Device_49
18361 0 unstable device for pfet_dev_SCG_Device_48
18362 0 unstable device for pfet_dev_TG_Device_47
18363 0 unstable device for pfet_dev_psp_HV_Device_46
18364 0 unstable device for pfet_dev_HV_Device_45
18365 0 unstable device for pfet_dev_psp_MV_Device_44
18366 0 unstable device for pfet_dev_MV_Device_43
18367 0 unstable device for pfet_dev_psp_Device_42
18368 0 unstable device for pfet_dev_Device_41
18369 0 unstable device for nfet_dev_psp_b_Device_40
18370 0 unstable device for nfet_dpw_psp_b_Device_39
18371 0 unstable device for nfet_dev_b_Device_38
18372 0 unstable device for nfet_dpw_b_Device_37
18373 0 unstable device for nfet_dev_HVT_b_Device_36
18374 0 unstable device for nfet_dev_HVT_Device_35
18375 0 unstable device for nfet_dev_TG_Device_34
18376 0 unstable device for nfet_dpw_TG_Device_33
18377 0 unstable device for nfet_dev_psp_HV_Device_32
18378 0 unstable device for nfet_dpw_psp_HV_Device_31
18379 0 unstable device for nfet_dev_HV_Device_30
18380 0 unstable device for nfet_dpw_HV_Device_29
18381 0 unstable device for nfet_dev_psp_MV_Device_28
18382 0 unstable device for nfet_dpw_psp_MV_Device_27
18383 0 unstable device for nfet_dev_MV_Device_26
18384 0 unstable device for nfet_dpw_MV_Device_25
18385 0 unstable device for nfzv_dev_HV_Device_24
18386 0 unstable device for nfzv_dev_Device_23
18387 0 unstable device for nfet_dev_psp_Device_22
18388 0 unstable device for nfet_dpw_psp_Device_21
18389 0 unstable device for nfet_dev_Device_20
18390 0 unstable device for nfet_dpw_Device_19
18391 0 unstable device for nfet6_dev_TG_Device_18
18392 0 unstable device for nfeti_dev_TG_Device_17
18393 0 unstable device for nfet6_dev_psp_HV_Device_16
18394 0 unstable device for nfet6_dev_HV_Device_15
18395 0 unstable device for nfeti_dev_psp_HV_Device_14
18396 0 unstable device for nfeti_dev_HV_Device_13
18397 0 unstable device for nfet6_dev_psp_MV_Device_12
18398 0 unstable device for nfet6_dev_MV_Device_11
18399 0 unstable device for nfeti_dev_psp_MV_Device_10
18400 0 unstable device for nfeti_dev_MV_Device_9
18401 0 unstable device for nfet6_dev_psp_b_Device_8
18402 0 unstable device for nfet6_dev_b_Device_7
18403 0 unstable device for nfet6_dev_psp_Device_6
18404 0 unstable device for nfet6_dev_Device_5
18405 0 unstable device for nfeti_dev_psp_b_Device_4
18406 0 unstable device for nfeti_dev_b_Device_3
18407 0 unstable device for nfeti_dev_psp_Device_2
18408 0 unstable device for nfeti_dev_Device_1
