*******************************************************************************
****** CMOS_SRAM_CELL schematic Final_Project_5020  <vs>  CMOS_SRAM_CELL layout Final_Project_5020
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(subc) Generic                                    1       1
(pfet) Generic                                    2       2
(nfet) Generic                                    4       4
                                             ------  ------
Total                                             7       7

Filter Statistics
=================                               Original            Filtered
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 4       4           4       4
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 2       2           2       2
(subc) Generic                                    1       1           1       1

Reduce Statistics
=================                               Filtered             Reduced
Cell/Device                               schematic  layout   schematic  layout
(nfet) Generic                                    0       0           0       0
(nfet_m0) Generic                                 4       4           4       4
(pfet) Generic                                    0       0           0       0
(pfet_m0) Generic                                 2       2           2       2
(subc) Generic                                    1       1           1       1
                                             ------  ------      ------  ------
Total                                             7       7           7       7

Schematic and Layout Match
